package com.rpm.prototype;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.util.*;

/** Entry content is a page. Only short choices and explicit confirmations use dialogs. */
public final class EntryActivity extends Activity {
    private Store store;
    private long id;
    private String page="detail",draftTitle,draftMinutes,draftNotes;
    private EditText titleInput,minutesInput,notesInput;
    private android.window.OnBackInvokedCallback backCallback;
    @Override public void onCreate(Bundle state){super.onCreate(state);Ui.theme(this);store=new Store(this);id=getIntent().getLongExtra("entry",-1);if(state!=null){page=state.getString("page","detail");draftTitle=state.getString("title");draftMinutes=state.getString("minutes");draftNotes=state.getString("notes");}render();}
    // API 26–32 fallback; API 33+ uses the OnBackInvokedCallback registered below.
    @android.annotation.SuppressLint("GestureBackNavigation")
    @Override public void onBackPressed(){back();}
    private void back(){if(!page.equals("detail")){rememberEdit();page="detail";render();}else finish();}
    private void render(){
        Ui.theme(this);JSONObject e;try{e=store.get(id);}catch(Exception ex){finish();return;}
        if(android.os.Build.VERSION.SDK_INT>=33){if(backCallback!=null)getOnBackInvokedDispatcher().unregisterOnBackInvokedCallback(backCallback);backCallback=null;if(!page.equals("detail")){backCallback=this::back;getOnBackInvokedDispatcher().registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT,backCallback);}}
        if(page.equals("edit")){edit(e);return;}if(page.equals("history")){history(e);return;}
        boolean plan=e.optString("kind").equals("plan");LinearLayout root=Ui.column(this);root.setBackgroundColor(Ui.PAPER);LinearLayout bar=Ui.toolbar(this,plan?"Action":"Check-in",this::back);bar.addView(Ui.iconButton(this,R.drawable.ic_edit,"Edit entry",()->{page="edit";render();}));root.addView(bar);
        LinearLayout body=body(root);body.addView(Ui.text(this,plan?(e.optInt("done")==1?"Done":"Planned action"):"Reported moment",14,Ui.ACCENT));Ui.gap(body,12);TextView title=Ui.heading(this,e.optString("title"),28);title.setTextIsSelectable(true);body.addView(title);Ui.gap(body,12);body.addView(Ui.text(this,"Saved "+Ui.date(e.optLong("created")),12,Ui.MUTED));
        if(!e.optString("notes").isEmpty()){Ui.gap(body,24);TextView notes=Ui.text(this,e.optString("notes"),16,Ui.NAVY);notes.setTextIsSelectable(true);body.addView(notes);}
        Ui.section(body,"Details");LinearLayout details=group(body);
        details.addView(Ui.option(this,R.drawable.ic_clock,plan?"Estimated duration":"Reported duration",e.isNull("minutes")?"Not recorded":e.optInt("minutes")+" minutes"+(e.optString("duration_source").equals("default_estimate")?" · suggested":""),()->{page="edit";render();}));
        if(plan){Ui.divider(details);details.addView(Ui.option(this,R.drawable.ic_calendar,"Planned time",e.isNull("planned")?"Not set":Ui.date(e.optLong("planned")),()->planned(e)));}
        if(!plan){Ui.divider(details);details.addView(Ui.option(this,R.drawable.ic_checkin,"Mood & energy",(e.isNull("mood")?"Mood not recorded":e.optString("mood"))+(e.isNull("energy")?"":" · "+e.optString("energy")+" energy"),()->feelings(e)));}
        Ui.section(body,"Context · optional");LinearLayout context=group(body);context.addView(Ui.option(this,R.drawable.ic_purpose,"Purpose",e.optString("purpose").isEmpty()?"Why does this matter?":e.optString("purpose"),()->EntryDialogs.purpose(this,store,e.optString("purpose"),p->{ContentValues v=new ContentValues();v.put("purpose",p);update(v,"Purpose selected");})));Ui.divider(context);
        String project="Unfiled";for(JSONObject p:store.projects())if(p.optLong("_id")==e.optLong("project",-1))project=p.optString("result");context.addView(Ui.option(this,R.drawable.ic_results,"Result",project,this::groupEntry));
        if(plan){Ui.section(body,"Alerts");LinearLayout alerts=group(body);
            if(e.optString("alarm_status").equals("none")&&e.optString("reminder_status").equals("none")){alerts.addView(Ui.option(this,R.drawable.ic_remind,"Reminder or alarm",e.optInt("done")==1?"Reopen this action to add an alert":"No alert set",()->{if(e.optInt("done")==0)EntryDialogs.reminder(this,store,id,this::render);}));}
            else{
                if(!e.optString("reminder_status").equals("none"))alerts.addView(Ui.option(this,R.drawable.ic_remind,"Notification reminder",alertText(e,"reminder"),()->alertOptions(false,e)));
                if(!e.optString("alarm_status").equals("none")){if(alerts.getChildCount()>0)Ui.divider(alerts);alerts.addView(Ui.option(this,R.drawable.ic_clock,"Ringing alarm",alertText(e,"alarm"),()->alertOptions(true,e)));}
                if(e.optInt("done")==0){Ui.divider(alerts);alerts.addView(Ui.option(this,R.drawable.ic_capture,"Add or change an alert","",()->EntryDialogs.reminder(this,store,id,this::render)));}
            }
        }
        Ui.section(body,"History");body.addView(Ui.option(this,R.drawable.ic_history,"Original input & edits","See what changed",()->{page="history";render();}));Ui.gap(body,16);
        if(plan){LinearLayout dock=Ui.column(this);Ui.padding(dock,20,8,20,12);dock.addView(Ui.button(this,e.optInt("done")==0?"Mark done":"Reopen action",true,()->{ContentValues v=new ContentValues();v.put("done",e.optInt("done")==0?1:0);if(e.optInt("done")==0){Reminders.cancel(this,id);Alarms.cancel(this,id);v.putNull("reminder");v.put("reminder_status","none");v.putNull("alarm");v.put("alarm_status","none");}update(v,"User changed completion; no actual duration or mood inferred");}));root.addView(dock);}
        show(root);
    }
    private String alertText(JSONObject e,String type){String status=e.optString(type+"_status").replace('_',' ');return Character.toUpperCase(status.charAt(0))+status.substring(1)+(e.isNull(type)?"":" · "+Ui.date(e.optLong(type)));}
    private void alertOptions(boolean alarm,JSONObject e){new AlertDialog.Builder(this).setTitle(alarm?"Ringing alarm":"Notification reminder").setItems(new String[]{"Change time","Cancel alert"},(d,w)->{if(w==0){if(alarm)EntryDialogs.alarm(this,store,id,this::render);else EntryDialogs.notificationReminder(this,store,id,this::render);}else{if(alarm)Alarms.cancel(this,id);else Reminders.cancel(this,id);ContentValues v=new ContentValues();v.putNull(alarm?"alarm":"reminder");v.put(alarm?"alarm_status":"reminder_status","none");update(v,"User canceled "+(alarm?"alarm":"reminder"));}}).show();}
    private void planned(JSONObject e){Runnable choose=()->EntryDialogs.time(this,e.isNull("planned")?System.currentTimeMillis()+3600000:e.optLong("planned"),at->{ContentValues v=new ContentValues();v.put("planned",at);update(v,"Planned time selected; alert times unchanged");});if(e.isNull("planned")){choose.run();return;}new AlertDialog.Builder(this).setTitle("Planned time").setItems(new String[]{"Change time","Clear planned time"},(d,w)->{if(w==0)choose.run();else{ContentValues v=new ContentValues();v.putNull("planned");update(v,"Planned time cleared; alert times unchanged");}}).show();}
    private void feelings(JSONObject e){LinearLayout form=Ui.column(this);Ui.pad(form,20);String[] moods={"Not recorded","Low","Uneasy","Okay","Good","Great"},energies={"Not recorded","Low","Medium","High"};form.addView(Ui.text(this,"Mood",14,Ui.MUTED));Spinner mood=spinner(moods,e.optString("mood"));form.addView(mood);Ui.gap(form,16);form.addView(Ui.text(this,"Energy",14,Ui.MUTED));Spinner energy=spinner(energies,e.optString("energy"));form.addView(energy);new AlertDialog.Builder(this).setTitle("Mood & energy").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{ContentValues v=new ContentValues();if(mood.getSelectedItemPosition()==0)v.putNull("mood");else v.put("mood",mood.getSelectedItem().toString());if(energy.getSelectedItemPosition()==0)v.putNull("energy");else v.put("energy",energy.getSelectedItem().toString());update(v,"User corrected mood and energy");}).show();}
    private Spinner spinner(String[] values,String selected){Spinner s=new Spinner(this);s.setMinimumHeight(Ui.dp(this,48));s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values));for(int i=0;i<values.length;i++)if(values[i].equals(selected))s.setSelection(i);return s;}
    private void groupEntry(){List<JSONObject> ps=store.projects();String[] labels=new String[ps.size()+1];labels[0]="Unfiled";for(int i=0;i<ps.size();i++)labels[i+1]=ps.get(i).optString("result");new AlertDialog.Builder(this).setTitle("Link to a result").setItems(labels,(d,w)->{ContentValues v=new ContentValues();if(w==0)v.putNull("project");else v.put("project",ps.get(w-1).optLong("_id"));update(v,"User chose optional grouping");}).show();}
    private void edit(JSONObject e){LinearLayout root=Ui.column(this);root.setBackgroundColor(Ui.PAPER);root.addView(Ui.toolbar(this,"Edit entry",this::back));LinearLayout body=body(root);titleInput=Ui.input(this,"What would you like to remember?");titleInput.setText(draftTitle==null?e.optString("title"):draftTitle);titleInput.setMinLines(2);Ui.field(body,"Entry",titleInput);minutesInput=Ui.input(this,"Minutes");minutesInput.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);minutesInput.setText(draftMinutes==null?(e.isNull("minutes")?"":e.optString("minutes")):draftMinutes);Ui.field(body,e.optString("kind").equals("plan")?"Estimated minutes":"Reported actual minutes · optional",minutesInput);notesInput=Ui.input(this,"Anything else?");notesInput.setMinLines(3);notesInput.setText(draftNotes==null?e.optString("notes"):draftNotes);Ui.field(body,"Notes · optional",notesInput);body.addView(Ui.text(this,"Your original input stays in the entry's history.",12,Ui.MUTED));LinearLayout dock=Ui.column(this);Ui.padding(dock,20,8,20,12);dock.addView(Ui.button(this,"Save changes",true,()->saveEdit(e)));root.addView(dock);show(root);}
    private void saveEdit(JSONObject e){String title=titleInput.getText().toString().trim(),minutes=minutesInput.getText().toString().trim();if(title.isEmpty()){titleInput.setError("Add a few words");titleInput.requestFocus();return;}boolean plan=e.optString("kind").equals("plan");int n=0;try{if(!minutes.isEmpty()){n=Integer.parseInt(minutes);if(n<1||n>1440)throw new NumberFormatException();}else if(plan)throw new NumberFormatException();}catch(NumberFormatException ex){minutesInput.setError("Use 1–1440 minutes");minutesInput.requestFocus();return;}ContentValues v=new ContentValues();v.put("title",title);v.put("notes",notesInput.getText().toString());if(minutes.isEmpty())v.putNull("minutes");else v.put("minutes",n);v.put("duration_source",plan?"chosen_estimate":minutes.isEmpty()?"not_reported":"reported_actual");try{store.update(id,v,"User edited title, duration or notes; raw input retained");draftTitle=draftMinutes=draftNotes=null;page="detail";((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(titleInput.getWindowToken(),0);render();}catch(Exception ex){EntryDialogs.error(this,ex);}}
    private void rememberEdit(){if(page.equals("edit")&&titleInput!=null){draftTitle=titleInput.getText().toString();draftMinutes=minutesInput.getText().toString();draftNotes=notesInput.getText().toString();}}
    private void history(JSONObject e){LinearLayout root=Ui.column(this);root.setBackgroundColor(Ui.PAPER);root.addView(Ui.toolbar(this,"Original input & edits",this::back));LinearLayout body=body(root);body.addView(Ui.heading(this,"Original input",14));Ui.gap(body,12);TextView original=Ui.text(this,e.optString("raw"),16,Ui.NAVY);original.setTextIsSelectable(true);body.addView(original);Ui.section(body,"Edits");for(JSONObject r:store.query("SELECT * FROM revisions WHERE entry_id=? ORDER BY _id DESC",new String[]{""+id})){LinearLayout card=Ui.card(this);card.addView(Ui.text(this,Ui.date(r.optLong("at")),12,Ui.MUTED));Ui.gap(card,8);card.addView(Ui.heading(this,r.optString("reason"),16));try{JSONObject snapshot=new JSONObject(r.optString("snapshot"));Ui.gap(card,8);card.addView(Ui.text(this,snapshot.optString("title"),16,Ui.NAVY));if(!snapshot.isNull("minutes")){Ui.gap(card,8);card.addView(Ui.text(this,snapshot.optInt("minutes")+(snapshot.optString("kind").equals("plan")?" min estimate":" min reported"),14,Ui.MUTED));}}catch(Exception ignored){}body.addView(card);}show(root);}
    private LinearLayout body(LinearLayout root){ScrollView scroll=new ScrollView(this);scroll.setVerticalScrollBarEnabled(false);LinearLayout body=Ui.column(this);Ui.padding(body,20,24,20,24);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));return body;}
    private LinearLayout group(LinearLayout parent){LinearLayout group=Ui.column(this);group.setBackground(Ui.bg(Ui.SURFACE,16,this));parent.addView(group);return group;}
    private void show(LinearLayout root){setContentView(root);Ui.insets(this,root);}
    private void update(ContentValues values,String why){try{store.update(id,values,why);render();}catch(Exception ex){EntryDialogs.error(this,ex);}}
    @Override protected void onSaveInstanceState(Bundle state){super.onSaveInstanceState(state);rememberEdit();state.putString("page",page);state.putString("title",draftTitle);state.putString("minutes",draftMinutes);state.putString("notes",draftNotes);}
    @Override protected void onDestroy(){store.close();super.onDestroy();}
}
