import test from 'node:test';
import assert from 'node:assert/strict';
import {snapshot,installDiagnostics} from './diagnostics.mjs';
function fixture(){const events=[],calls=[],listeners=new Map();let now=10,seq=0;const host={console:Object.fromEntries(['log','debug','info','warn','error','assert','table','time','timeEnd','count'].map(m=>[m,function(...args){calls.push({m,args,self:this});}])),RpmNative:{diagnostic:body=>events.push(JSON.parse(body))},addEventListener:(k,v)=>listeners.set(k,v),removeEventListener:k=>listeners.delete(k)};const logger=installDiagnostics({host,sessionId:'test-session',id:()=>`test-id-${++seq}`,clock:()=>now});return {host,logger,events,calls,listeners,advance:ms=>now+=ms};}
test('snapshots errors, circular data and getters without executing arbitrary code',()=>{const value={number:3,secret:'hide',error:new Error('failure')};value.circular=value;Object.defineProperty(value,'expensive',{enumerable:true,get(){throw new Error('must not run');}});const copy=snapshot(value);assert.equal(copy.circular,'[Circular]');assert.equal(copy.expensive,'[Getter]');assert.equal(copy.error.message,'failure');assert.match(copy.error.stack,/failure/);assert.equal(copy.secret,'[REDACTED]');});
test('redacts sensitive keys, headers, provider keys and URL credentials while preserving personal words',()=>{const value=snapshot({raw:'My synthetic personal capture',api_key:'NEVER',authorization:'Bearer NEVER',nested:['https://name:NEVER@example.com/?token=NEVER','sk-or-v1-NEVER-1234567890','password=NEVER'],cookie:'NEVER'});assert.equal(value.raw,'My synthetic personal capture');assert.ok(!JSON.stringify(value).includes('NEVER'));});
test('captures arguments immediately and preserves original console behavior',()=>{const f=fixture(),obj={text:'before'};f.host.console.log('capture',obj);obj.text='after';assert.equal(f.calls.length,1);assert.equal(f.calls[0].self,f.host.console);assert.equal(f.events[0].payload.args[1].text,'before');f.logger.restore();f.host.console.log('later');assert.equal(f.events.length,1);});
test('keeps full capture unsampled, false assertions, timers and counters',()=>{const f=fixture();for(let i=0;i<25;i++)f.host.console.info(i);f.host.console.assert(true,'ignore');assert.equal(f.events.length,25);f.host.console.assert(false,'failure');assert.equal(f.events.at(-1).level,'error');f.host.console.time('work');f.advance(41);f.host.console.timeEnd('work');assert.equal(f.events.at(-1).payload.durationMs,41);f.host.console.count('work');f.host.console.count('work');assert.equal(f.events.at(-1).payload.count,2);});
test('captures global errors and unhandled rejections with stacks',()=>{const f=fixture();f.listeners.get('error')({error:new Error('boom'),filename:'runtime.js',lineno:3});f.listeners.get('unhandledrejection')({reason:new Error('async')});assert.deepEqual(f.events.map(e=>e.kind),['exception','rejection']);assert.match(f.events[1].payload.error.stack,/async/);});
test('emits exactly one outcome per overlapping operation including handled errors',async()=>{const f=fixture();let release;const wait=new Promise(r=>release=r);const first=f.logger.track('capture',{operationId:'one'},async()=>{await wait;return {status:'interpreted'};});await f.logger.track('capture',{operationId:'two'},async()=>({status:'captured',error:'offline'}));f.advance(99);release();await first;assert.equal(f.events.length,2);assert.equal(f.events[0].operationId,'two');assert.equal(f.events[0].outcome,'error');assert.equal(f.events[1].operationId,'one');assert.equal(f.events[1].payload.durationMs,99);});
test('throwing operations preserve the error and logging failure does not replace it',async()=>{const f=fixture();f.host.RpmNative.diagnostic=()=>{throw new Error('transport');};const original=new Error('actual');await assert.rejects(f.logger.track('save',{operationId:'x'},()=>Promise.reject(original)),e=>e===original);assert.doesNotThrow(()=>f.host.console.error(original));});
test('huge and hostile arguments remain bounded and serializable',()=>{const a=Array.from({length:100},()=>('界'.repeat(24000)));assert.ok(new TextEncoder().encode(JSON.stringify(snapshot(a))).length<48000);assert.doesNotThrow(()=>snapshot(new Proxy({},{ownKeys(){throw new Error('no');}})));assert.equal(snapshot(123n),'123');});
test('a throwing console argument coercion cannot introduce an app error',()=>{const f=fixture();const hostile={[Symbol.toPrimitive](){throw new Error('no coercion');}};assert.doesNotThrow(()=>f.host.console.log(hostile));assert.equal(f.events.length,1);});
