import {planner,tasks,blockTasks,totals,localDay,shiftDay,dayRange,timelineItems,conflicts,alternatives} from './planner-state.mjs';
import {planningRequest,readPlanningResponse} from './planner-ai.mjs';
import {repeats,nextOccurrence,occurrences} from './planner-recurrence.mjs';
import {calendarLabel,calendarRisk,calendarRows} from './planner-calendar.mjs';

const paths={back:'m14 5-7 7 7 7',next:'m9 5 7 7-7 7',up:'m5 14 7-7 7 7',down:'m5 9 7 7 7-7',plus:'M12 5v14M5 12h14',close:'m6 6 12 12M18 6 6 18',star:'m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z',check:'m5 12 4 4L19 6',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',grip:'M8 6h1m6 0h1M8 12h1m6 0h1M8 18h1m6 0h1'};
const el=(tag,cls='',text='')=>{const n=document.createElement(tag);n.className=cls;n.textContent=text;return n;};
const button=(label,fn,cls='')=>{const n=el('button',cls,label);n.type='button';n.addEventListener('click',fn);return n;};
const icon=(name,label,fn)=>{const n=button('',fn,'icon');n.setAttribute('aria-label',label);const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',paths[name]);svg.append(p);n.append(svg);return n;};
const clock=value=>new Date(value).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});
const duration=m=>m==null?'Set time':m>=60?`${Math.floor(m/60)}h${m%60?' '+m%60+'m':''}`:`${m}m`;
const datetime=value=>{if(!value)return '';const d=new Date(value);return localDay(d)+'T'+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');};
Object.assign(paths,{layers:'m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5',folder:'M3 7V5h6l2 2h10v13H3V7Z',life:'M12 21V11m0 5C4 16 3 9 3 5c7 0 9 4 9 9m0-3c0-5 4-8 9-8 0 7-3 11-9 11',more:'M5 12h.01M12 12h.01M19 12h.01',capture:'M4 4h16v12H9l-5 4V4Z',trash:'M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7'});
Object.assign(paths,{calendar:'M5 5h14a2 2 0 0 1 2 2v13H3V7a2 2 0 0 1 2-2ZM7 3v4m10-4v4M3 10h18',sigma:'M19 4H5l7 8-7 8h14',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14Zm5 12 6 6',edit:'m15 4 5 5M4 20l1-6L16 3l5 5L10 19l-6 1Z',person:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM4 21v-3a8 6 0 0 1 16 0v3',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Zm0 4v5l4 2',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z',target:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Zm0 5a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z'});
const svgNode=(tag,attrs)=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);return n;};
const mark=name=>{const svg=svgNode('svg',{viewBox:'0 0 24 24','aria-hidden':'true',class:'symbol'});svg.append(svgNode('path',{d:paths[name]}));return svg;};
const palette=['cyan','violet','mint','amber','coral'];
const toneFor=value=>palette[[...String(value??'')].reduce((sum,c)=>sum+c.charCodeAt(0),0)%palette.length];
const doneStats=rows=>({done:rows.filter(e=>e.done).length,total:rows.length,percent:rows.length?Math.round(rows.filter(e=>e.done).length/rows.length*100):0});

export function mountPlanner(api){
  const $=id=>document.getElementById(id),work=$('workspace'),editor=$('editor');let day=localDay(),level=0,projectId=null,focusedBlockId=null,focusedTaskId=null,year=new Date().getFullYear(),saving=false,calendar=[],calendarState='Checking…',noticeTimer,returnFocus,calendarSerial=0,lastRenderedKey=null,suppressClick=false;
  const positions=new Map(),positionKey=()=>`${level}:${level===0?day:level===2?projectId:level===3?year:'blocks'}`;
  let reviewToken=null,scheduleWorking=false,editorVersion=null,draftKey=null,draftValues={},dayAsList=api.getPhone().fontScale>=1.5;
  let rpmFilter=null,projectFilter=null,lifeFilter=null,horizon='yearly',period=new Date().getMonth()+1;
  const mustOnly=new Set(),collapsedProjects=new Set(),collapsedAreas=new Set();
  function rememberField(label,n){if(!draftKey)return;const cached=draftValues[label];if(cached!==undefined){if(n.type==='checkbox')n.checked=!!cached;else if(n.tagName!=='SELECT'||[...n.options].some(o=>o.value===cached))n.value=cached;}const record=()=>{draftValues[label]=n.type==='checkbox'?n.checked:n.value;try{localStorage.setItem('rpm-planner-draft:'+draftKey,JSON.stringify(draftValues));}catch{}};n.addEventListener('input',record);n.addEventListener('change',record);}
  function discardDraft(){if(draftKey)try{localStorage.removeItem('rpm-planner-draft:'+draftKey);}catch{}draftKey=null;draftValues={};}
  const data=()=>api.getData(),p=()=>planner(data());
  function notice(message,canUndo=false){const n=$('notice');clearTimeout(noticeTimer);n.replaceChildren(el('span','',message));if(canUndo)n.append(button('Undo',async()=>{try{await api.commit({type:'undo'});n.hidden=true;render(false);}catch(e){notice(e.message);}}));n.hidden=false;noticeTimer=setTimeout(()=>n.hidden=true,6000);}
  async function commit(op,keepEditor=false){if(saving)return;saving=true;try{if(!editor.hidden&&editorVersion!==data().version)throw new Error('Saved data changed while editing. Go back and reopen this draft to review it.');const id=await api.commit(op);editorVersion=data().version;if(!keepEditor){discardDraft();closeEditor();}render(false);notice('Saved on this phone',true);return id;}catch(e){const err=editor.querySelector('.edit-error');if(err)err.textContent=e.message;else notice(e.message);throw e;}finally{saving=false;}}
  function closeEditor(){editor.hidden=true;editor.replaceChildren();$('planner').inert=false;returnFocus?.focus({preventScroll:true});}
  function openEditor(title,key=null){editorVersion=data().version;draftKey=key;draftValues={};if(key)try{draftValues=JSON.parse(localStorage.getItem('rpm-planner-draft:'+key)??'{}');}catch{}returnFocus=document.activeElement;editor.hidden=false;editor.className=key?'form-sheet':'detail-sheet';editor.setAttribute('aria-label',title);editor.replaceChildren();$('planner').inert=true;const header=el('header','toolbar');const back=icon('close','Back to planner',closeEditor);header.append(el('h2','',title),back);const body=el('div','edit-body'),actions=el('div','edit-actions');editor.append(header,body,actions);if(Object.keys(draftValues).length)body.append(el('p','muted small','Draft restored. Review the details before saving.'));back.focus({preventScroll:true});return {body,actions};}
  function field(body,label,value,type='text'){const wrap=el('label','field'),n=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')n.type=type;n.value=value??'';rememberField(label,n);wrap.append(el('span','',label),n);body.append(wrap);return n;}
  function select(body,label,value,options){const wrap=el('label','field'),n=el('select');for(const [v,t] of options){const o=el('option','',t);o.value=v;n.append(o);}n.value=value??'';rememberField(label,n);wrap.append(el('span','',label),n);body.append(wrap);return n;}
  function checkbox(body,label,value){const wrap=el('label','check-field'),n=el('input');n.type='checkbox';n.checked=!!value;rememberField(label,n);wrap.append(n,el('span','',label));body.append(wrap);return n;}
  function changeLevel(next){if(next<0||next>3||next===level)return;const old=level;level=next;focusedTaskId=null;focusedBlockId=null;render(true,next>old?'up':'down');}
  function shiftLifePeriod(delta){if(horizon==='monthly'||horizon==='quarterly'){period+=delta*(horizon==='monthly'?1:3);if(period>12){year++;period-=12;}if(period<1){year--;period+=12;}}else year+=delta;render(true);}
  function horizontal(direction){if(!editor.hidden)return;if(level===0){day=shiftDay(day,direction);render(true,direction>0?'right':'left');}else if(level===2&&p().projects.length){const ids=p().projects.map(x=>x.id),i=Math.max(0,ids.indexOf(projectId));showProject(ids[(i+direction+ids.length)%ids.length]);}else if(level===3&&horizon!=='values')shiftLifePeriod(direction);}
  function swipe(node,vertical=false){let start;node.addEventListener('pointerdown',e=>{if(e.target.closest('input,textarea,select,.resize,.drag-handle,.task-row,.filter-strip'))return;start={x:e.clientX,y:e.clientY};});node.addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.5){suppressClick=true;horizontal(dx<0?1:-1);}else if(vertical&&Math.abs(dy)>65&&Math.abs(dy)>Math.abs(dx)*1.5){suppressClick=true;changeLevel(level+(dy<0?1:-1));}if(suppressClick)setTimeout(()=>suppressClick=false,400);});node.addEventListener('pointercancel',()=>start=null);node.addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopImmediatePropagation();suppressClick=false;}},true);}
  function capture(){const focus={view:['day','rpm','projects','life'][level],day,taskId:focusedTaskId,blockId:focusedBlockId,projectId:level===2?projectId:null};try{localStorage.setItem('rpm-capture-context',JSON.stringify(focus));}catch{}api.native('capture').catch(e=>notice(e.message));}
  function navigation(){document.documentElement.dataset.largeText=String(api.getPhone().fontScale>=1.5);$('planner').dataset.view=['daily','rpm','projects','life'][level];const nav=$('planner-tabs');nav.replaceChildren();for(const [i,name,label] of [[0,'calendar','Daily'],[1,'sigma','RPM'],[2,'folder','Projects'],[3,'life','Life']]){const tab=icon(name,label,()=>i===level&&i===0?datePicker():changeLevel(i));tab.title=label;tab.setAttribute('aria-current',level===i?'page':'false');nav.append(tab);}nav.append(icon('settings','Settings',()=>api.native('settings').catch(e=>notice(e.message))));
    const f=$('planner-actions');f.replaceChildren(icon('search','Search plans',searchPlans),icon('plus','Add or capture',quickAdd));f.lastChild.classList.add('primary');
    const header=$('view-header');header.replaceChildren();header.hidden=level===1;
    if(level===0){const strip=el('div','week-strip'),selected=new Date(day+'T12:00'),monday=shiftDay(day,-((selected.getDay()+6)%7));for(let i=0;i<7;i++){const key=shiftDay(monday,i),date=new Date(key+'T12:00'),b=button('',()=>{if(key===day)datePicker();else{day=key;render(true);}},'week-day');b.setAttribute('aria-label',date.toLocaleDateString('en',{weekday:'long',day:'numeric',month:'long',year:'numeric'}));b.setAttribute('aria-pressed',String(key===day));b.append(el('small','',date.toLocaleDateString('en',{weekday:'short'}).toUpperCase()),el('span','numeric',String(date.getDate())));const dots=el('span','day-dots');for(const e of timelineItems(data(),key,calendar).slice(0,3)){const dot=el('i');dot.dataset.tone=e.source==='calendar'?'cyan':toneFor(e.blockId??e.id);dots.append(dot);}b.append(dots);strip.append(b);}header.append(strip);const active=strip.querySelector('[aria-pressed=true]');strip.scrollLeft=active.offsetLeft-strip.offsetLeft-(strip.clientWidth-active.offsetWidth)/2;swipe(strip);}
    else if(level>1){const title=el('div','view-title');title.append(el('span','status-dot'),el('h1','',level===2?'Projects':'Life Vision'));header.append(title,icon('person','Open settings',()=>api.native('settings').catch(e=>notice(e.message))));}
  }
  function quickAdd(){const {body}=openEditor('Add to your plan');body.append(button(['Add a task','New RPM block','New project','New goal'][level],()=>level===0?taskEditor(null,{plannedDate:day}):entityEditor(['','blocks','projects','goals'][level]),'menu-action link'),button('Capture with AI',capture,'menu-action link'));if(level!==0)body.append(button('Add a task',()=>taskEditor(null),'menu-action link'));if(level===0)body.append(button(`Unscheduled tasks · ${tasks(data()).filter(e=>!e.planned&&!e.done).length}`,showUnscheduled,'menu-action link'),button('Choose date or calendar',datePicker,'menu-action link'));if(level===1)body.append(button('Sort into RPM blocks',()=>aiAction('sort'),'menu-action link'),button('Examples',examples,'menu-action link'),button('Trash',showTrash,'menu-action link'));if(level===3)body.append(button('Manage life areas',areaPicker,'menu-action link'),button('Goal ideas',()=>aiAction('ideas'),'menu-action link'),button('Goals and vision',contextEditor,'menu-action link'));}
  function searchPlans(){const {body}=openEditor('Search plans'),input=field(body,'Search tasks, blocks, projects and goals','', 'search'),results=el('div','search-results');body.append(results);const draw=()=>{results.replaceChildren();const q=input.value.trim().toLocaleLowerCase();if(!q){results.append(button('Capture with AI',capture,'menu-action link'),button('Unscheduled tasks',showUnscheduled,'menu-action link'));return;}const groups=[['Task',tasks(data()),e=>taskDetails(e.id)],['RPM block',p().blocks,e=>openBlock(e.id)],['Project',p().projects,e=>{projectId=e.id;projectFilter=null;level=2;closeEditor();render(true);work.querySelector('[data-project-id="'+e.id+'"]')?.scrollIntoView({block:'start'});} ],['Goal',p().goals,e=>entityEditor('goals',e.id)]];let count=0;for(const [label,items,open] of groups)for(const item of items.filter(e=>(e.title+' '+(e.purpose??'')).toLocaleLowerCase().includes(q)).slice(0,30)){const b=button('',()=>open(item),'menu-action search-result');b.append(el('small','muted',label),el('span','',item.title));results.append(b);count++;}if(!count)results.append(el('p','empty','No matching plans. Try another word.'));};input.addEventListener('input',draw);draw();}
  function datePicker(){const {body,actions}=openEditor('Choose date');const date=field(body,'Date',day,'date');body.append(button(`Calendar · ${calendarState}`,calendarEditor,'menu-action link'),button(dayAsList?'Show timeline':'Show day list',()=>{dayAsList=!dayAsList;positions.delete(positionKey());closeEditor();render(true);},'menu-action link'));actions.append(button('Today',()=>{day=localDay();closeEditor();render(true);},'secondary'),button('Go',()=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(date.value))return;day=date.value;closeEditor();render(true);},'primary'));}
  function render(reset=false,direction=''){if(level===2&&!p().projects.some(pr=>pr.id===projectId))projectId=p().projects[0]?.id??null;const changedView=lastRenderedKey!==positionKey(),scroll=work.scrollTop;if(lastRenderedKey)positions.set(lastRenderedKey,scroll);lastRenderedKey=positionKey();navigation();work.replaceChildren();work.className=direction?'shift-'+direction:'';if(level===0)renderDay();else if(level===1)renderRPM();else if(level===2)renderProjects();else renderLife();
    work.scrollTop=reset?(positions.get(lastRenderedKey)??(level===0&&!dayAsList?8*hourSize()-12:0)):scroll;
    if(level===0&&changedView)refreshCalendar();
  }
  const hourSize=()=>parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--hour'))||96;
  function fitTimelineCard(node){
    const style=getComputedStyle(node),title=node.querySelector('h3'),meta=node.querySelector('.event-meta'),block=node.querySelector('.block-name');
    const available=node.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom),titleLine=parseFloat(getComputedStyle(title).lineHeight),metaLine=parseFloat(getComputedStyle(meta).lineHeight);
    meta.hidden=available<titleLine+metaLine;
    const blockLine=block?parseFloat(getComputedStyle(block).lineHeight):0;
    if(block)block.hidden=meta.hidden||available<titleLine+metaLine+blockLine;
    const reserved=(meta.hidden?0:metaLine)+(block&&!block.hidden?blockLine:0);
    title.style.setProperty('--title-lines',Math.max(1,Math.min(3,Math.floor((available-reserved)/titleLine))));
  }
  function renderDay(){
    const range=dayRange(day),allDay=calendar.filter(e=>e.allDay&&e.start<range.end-3600000&&e.end>range.start);
    const dated=tasks(data()).filter(e=>!e.done&&!e.planned&&e.plannedDate===day);
    if(dayAsList){const list=el('div','scroll-page day-list');list.append(button('Show timeline',()=>{dayAsList=false;positions.delete(positionKey());render(true);},'link'));for(const e of timelineItems(data(),day,calendar)){const b=button('',()=>e.source==='calendar'?calendarDetails(e):taskDetails(e.id,e.occurrence),'agenda-item');b.dataset.tone=e.source==='calendar'?'cyan':toneFor(e.blockId??e.id);b.append(el('small','event-meta',e.allDay?'All day':clock(e.start)+' · '+duration(Math.round((e.end-e.start)/60000))),el('span','',e.title));list.append(b);}for(const e of dated)list.append(taskRow(e));if(list.children.length===1)list.append(emptyState('An open day','Add a task or leave room for what comes up.',()=>taskEditor(null,{plannedDate:day}),'Add a task'));work.append(list);return;}
    const canvas=el('div','timeline');work.append(canvas);
    for(let h=0;h<=24;h++){const line=el('div','hour-line');line.style.top=`${h*hourSize()}px`;line.append(el('span','hour-label',String(h%24).padStart(2,'0')+':00'));canvas.append(line);}
    const rows=timelineItems(data(),day,calendar.filter(e=>!e.allDay),48/hourSize()*60);
    for(const e of rows){const n=el('article','timed'+(e.source==='calendar'?' external':'')),top=Math.max(0,(e.start-range.start)/3600000)*hourSize(),height=Math.max(48,(Math.min(e.end,range.end)-Math.max(e.start,range.start))/3600000*hourSize());n.dataset.tone=e.source==='calendar'?'cyan':e.must?'amber':toneFor(e.blockId??e.id);n.style.top=top+'px';n.style.height=height+'px';n.style.left=`calc(54px + (100% - 54px) * ${e.lane/e.lanes})`;n.style.width=`calc((100% - 54px) / ${e.lanes} - 4px)`;const open=button('',()=>e.source==='calendar'?calendarDetails(e):taskDetails(e.id,e.occurrence),'open-event');open.setAttribute('aria-label',`${e.title}, ${clock(e.start)}, ${duration(Math.round((e.end-e.start)/60000))}`);open.append(el('div','event-meta',`${clock(e.start)} – ${clock(e.end)}`),el('h3','',e.title));const block=p().blocks.find(b=>b.id===e.blockId);open.append(el('div','block-name',e.source==='calendar'?'Calendar commitment':block?.title??(e.must?'Must do':'Personal task')));n.append(open);if(e.source==='rpm'){const handle=button('',()=>{},'resize');handle.setAttribute('aria-label','Resize '+e.title);installResize(handle,n,e);n.append(handle);}canvas.append(n);fitTimelineCard(n);}
    if(!rows.length){const empty=emptyState('An open day','Your scheduled tasks will appear here.',()=>taskEditor(null,{plannedDate:day}),'Add a task');empty.classList.add('timeline-empty');empty.style.top=(8.4*hourSize())+'px';canvas.append(empty);}
    const now=new Date();if(localDay(now)===day){const line=el('div','now-line');line.style.top=((+now-range.start)/3600000*hourSize())+'px';line.append(el('span','now-time',clock(now)));canvas.append(line);}
    if(allDay.length||dated.length){const tray=el('div','day-tray');tray.append(button(`${allDay.length+dated.length} without a time`,()=>{const {body}=openEditor('Today · without a time');allDay.forEach(e=>body.append(button(e.title,()=>calendarDetails(e),'menu-action link')));dated.forEach(e=>body.append(taskRow(e)));},'chip'));work.append(tray);}
  }
  function emptyState(title,description,action,label){const empty=el('div','empty');empty.append(el('h2','',title),el('p','',description));if(action)empty.append(button(label,action,'secondary'));return empty;}
  function installResize(handle,node,e){let start=null,moved=false;handle.addEventListener('pointerdown',ev=>{ev.stopPropagation();start={y:ev.clientY,minutes:e.minutes??30};moved=false;handle.setPointerCapture(ev.pointerId);});handle.addEventListener('pointermove',ev=>{if(!start)return;const delta=ev.clientY-start.y;if(Math.abs(delta)>6)moved=true;const minutes=Math.max(5,Math.min(1440,Math.round((start.minutes+delta/hourSize()*60)/5)*5));node.style.height=Math.max(48,minutes/60*hourSize())+'px';node.querySelector('.event-meta').textContent=clock(e.start)+' · '+duration(minutes);fitTimelineCard(node);start.next=minutes;});handle.addEventListener('pointerup',ev=>{ev.stopPropagation();const s=start;start=null;if(!s)return;if(moved)scheduleSave(e.id,{minutes:s.next,planned:e.planned}).catch(()=>{});else taskEditor(e.id);});handle.addEventListener('pointercancel',()=>{start=null;render(false);});handle.addEventListener('click',ev=>ev.stopPropagation());}
  async function scheduleSave(id,fields,allow=false){if(scheduleWorking)return;scheduleWorking=true;try{await checkedScheduleSave(id,fields,allow);}finally{scheduleWorking=false;}}
  async function checkedScheduleSave(id,fields,allow=false){
    if(saving)return;const existing=id?tasks(data()).find(e=>e.id===id):null,candidate={...existing,...fields};const planned=candidate.planned,minutes=candidate.minutes??30;
    let clashes=[],risk=null,anchor=planned;
    if(planned){anchor=repeats(candidate)?nextOccurrence(candidate):planned;const copy=await api.native('calendarRead',{anchor:Date.parse(anchor)});calendar=calendarRows(copy);calendarState=calendarLabel(copy);risk=calendarRisk(copy,Date.parse(anchor),Date.parse(anchor)+minutes*60000);
      const occurrencesToCheck=occurrences(candidate,Date.parse(anchor),Date.parse(anchor)+(repeats(candidate)?21*86400000:1));
      clashes=occurrencesToCheck.flatMap(o=>conflicts(data(),o.start,minutes,calendar,id)).filter((e,i,a)=>a.findIndex(x=>x.id===e.id&&x.start===e.start)===i);
    }
    const token=JSON.stringify({id,planned,minutes,recurrence:candidate.recurrence??null,repeatAfterDays:candidate.repeatAfterDays??null,clashes:clashes.map(e=>[e.id,e.start,e.end]),risk});
    if((clashes.length||risk)&&(!allow||reviewToken!==token)){reviewToken=token;taskEditor(id,fields,clashes,risk);return;}
    await commit({type:'saveTask',id,fields});reviewToken=null;
  }
  function taskDetails(id,occurrence){const e=tasks(data()).find(x=>x.id===id);if(!e){notice('This task is no longer available.');return;}focusedTaskId=id;focusedBlockId=e.blockId??null;const when=occurrence??(repeats(e)?nextOccurrence(e):e.planned);const {body,actions}=openEditor('Task');body.append(el('h2','detail-result',e.title),el('p','muted numeric',`${when?clock(when)+' · '+new Date(when).toLocaleDateString():'Unscheduled'} · ${duration(e.minutes)}`));if(repeats(e))body.append(el('p','muted',e.repeatAfterDays?`Repeats ${e.repeatAfterDays} days after completion. Done schedules the next task.`:`Repeats ${e.recurrence}. Done completes only this occurrence. Editing changes the series.`));const block=p().blocks.find(b=>b.id===e.blockId);for(const [label,value] of [['Result',block?.title],['Purpose',e.purpose||block?.purpose],['How / notes',e.notes],['Leverage',e.leverage],['Original capture',e.raw]])if(value){const s=el('section','detail-section');s.append(el('h3','',label),el('p','',value));body.append(s);}if(block)body.append(button('Open RPM block',()=>openBlock(block.id),'link'));const tools=el('div','row');tools.append(button('Ask AI',capture,'link'),button('Move',()=>movePicker(e),'link'),button('Delete task',()=>deleteTask(e),'danger'));body.append(tools);actions.append(button(e.done?'Reopen':repeats(e)?'Done this time':'Done',()=>toggleDone(e,when),'secondary'),button('Edit task',()=>taskEditor(id),'primary'));}
  function taskEditor(id,overrides={},clashes=[],risk=null){const e=id?tasks(data()).find(x=>x.id===id):{};if(!e)return;const v={...e,...overrides}, {body,actions}=openEditor(id?'Edit task':'New task','task:'+(id??'new'));if(Object.keys(overrides).length||clashes.length||risk)draftValues={};
    if(clashes.length||risk){const alert=el('div','conflict');if(clashes.length)alert.append(el('p','',`Overlaps ${clashes.slice(0,6).map(x=>x.title+' · '+new Date(x.start).toLocaleDateString([], {month:'short',day:'numeric'})+' '+clock(x.start)).join(', ')}`));if(risk)alert.append(el('p','',risk));const row=el('div','row');for(const t of clashes.length?alternatives(data(),repeats(v)?nextOccurrence(v):v.planned,v.minutes??30,calendar,id):[])row.append(button(`${localDay(t)===localDay(v.planned)?'':new Date(t).toLocaleDateString([], {weekday:'short'})+' '}${clock(t)}`,()=>taskEditor(id,{...v,planned:t}), 'secondary'));alert.append(row);body.append(alert);}
    const name=field(body,'Task',v.title),time=field(body,'Start · leave blank to keep unscheduled',datetime(v.planned),'datetime-local'),mins=field(body,'Estimated minutes',v.minutes??30,'number');mins.min='1';mins.max='1440';
    const repeat=select(body,'Repeat',v.repeatAfterDays?'after':v.recurrence??'',[['','Does not repeat'],['daily','Every day'],['weekdays','Weekdays'],['weekly','Every week'],['after','After completion']]),interval=field(body,'Days after completion',v.repeatAfterDays??1,'number');interval.min='1';interval.max='365';interval.parentElement.hidden=repeat.value!=='after';repeat.onchange=()=>interval.parentElement.hidden=repeat.value!=='after';
    body.append(el('p','muted small','Repeating-task edits apply to the series. Nearby conflicts are checked for 21 days; later dates can change.'));
    const block=select(body,'RPM block',v.blockId,[['','Unsorted'],...p().blocks.map(b=>[b.id,b.title])]),must=checkbox(body,'Must do',v.must),purpose=field(body,'Purpose',v.purpose,'textarea'),notes=field(body,'How / details',v.notes,'textarea'),leverage=field(body,'Leverage · person, tool or approach',v.leverage,'textarea'),alert=select(body,'Alert',Object.hasOwn(overrides,'alert')?overrides.alert:v.alertIntent?.type??'off',[['off','No alert'],['reminder','Reminder'],['alarm','Ringing alarm']]);const err=el('p','edit-error error');body.append(err);
    const save=async allow=>{try{const fields={title:name.value,planned:time.value?new Date(time.value).toISOString():null,plannedDate:time.value?null:v.plannedDate??null,minutes:mins.value?Number(mins.value):null,recurrence:repeat.value==='after'?null:repeat.value||null,repeatAfterDays:repeat.value==='after'?Number(interval.value):null,blockId:block.value||null,must:must.checked,purpose:purpose.value,notes:notes.value,leverage:leverage.value,alert:alert.value};await scheduleSave(id,fields,allow);}catch(e){err.textContent=e.message;}};actions.append(button('Cancel',()=>{discardDraft();closeEditor();}),button(clashes.length||risk?'Save anyway':'Save',()=>save(!!(clashes.length||risk)),'primary'));}
  function toggleDone(e,when){return commit(e.done?{type:'reopenTask',id:e.id}:{type:'saveTask',id:e.id,fields:{done:true},occurrence:when??(repeats(e)?nextOccurrence(e):e.planned)}).then(()=>{if(repeats(e))notice('Completed this occurrence. The next one stays active.',true);}).catch(()=>{});}
  function taskRow(e,index=null){const row=el('div','task-row'+(e.must?' must':'')+(e.done?' done':''));row.dataset.taskId=e.id;
    const check=button('',()=>toggleDone(e),'time-badge task-check numeric');check.setAttribute('aria-label',(e.done?'Reopen: ':'Complete: ')+e.title);check.setAttribute('role','checkbox');check.setAttribute('aria-checked',String(!!e.done));check.append(el('strong','',e.minutes==null?'—':String(e.minutes)),el('small','',e.done?'DONE':'MIN'));if(e.done)check.append(mark('check'));row.append(check);
    const name=button('',()=>taskDetails(e.id),'task-title');name.append(el('span','',e.title));if(e.planned)name.append(el('small','task-schedule',clock(repeats(e)?nextOccurrence(e):e.planned)+(repeats(e)?' · Repeats':'')));else if(e.plannedDate)name.append(el('small','task-schedule',new Date(e.plannedDate+'T12:00').toLocaleDateString('en',{day:'numeric',month:'short'})));if(e.must)name.append(el('small','must-label','Must do'));row.append(name);
    const star=icon('star',e.must?'Unmark must: '+e.title:'Mark must: '+e.title,()=>commit({type:'saveTask',id:e.id,fields:{must:!e.must}},true).catch(()=>{}));star.classList.toggle('must-on',!!e.must);star.setAttribute('aria-pressed',String(!!e.must));row.append(star);
    if(index!==null){const grip=button('',()=>priorityEditor(e),'drag-handle numeric');grip.append(mark('grip'),el('small','',String(index+1)));grip.setAttribute('aria-label',`Priority ${index+1}: move ${e.title}`);installOrder(grip,row,e);row.append(grip);}else row.append(icon('more','More actions: '+e.title,()=>taskActions(e)));
    installTaskSwipe(name,row,e);return row;
  }
  function installTaskSwipe(handle,row,e){let start=null,moved=false;handle.addEventListener('pointerdown',ev=>{start={x:ev.clientX,y:ev.clientY};moved=false;});handle.addEventListener('pointermove',ev=>{if(!start)return;const dx=ev.clientX-start.x,dy=ev.clientY-start.y;if(Math.abs(dy)>Math.abs(dx)&&!moved){start=null;return;}if(Math.abs(dx)>12){moved=true;handle.setPointerCapture(ev.pointerId);row.style.transform=`translateX(${Math.max(-80,Math.min(80,dx))}px)`;row.dataset.swipe=dx>0?'done':'must';}});const clear=()=>{start=null;row.style.transform='';delete row.dataset.swipe;};handle.addEventListener('pointerup',ev=>{if(!start)return;const dx=ev.clientX-start.x,dy=ev.clientY-start.y;clear();if(Math.abs(dx)>64&&Math.abs(dx)>Math.abs(dy)*1.5){moved=true;dx>0?toggleDone(e):commit({type:'saveTask',id:e.id,fields:{must:!e.must}},true).catch(()=>{});}});handle.addEventListener('pointercancel',clear);handle.addEventListener('click',ev=>{if(moved){ev.preventDefault();ev.stopImmediatePropagation();moved=false;}},true);}
  function priorityEditor(e){const rows=blockTasks(data(),e.blockId),i=rows.findIndex(t=>t.id===e.id),{body,actions}=openEditor('Priority');body.append(el('h2','detail-result',e.title),el('p','muted','Move to change priority. This does not change the scheduled time.'));const move=delta=>{const ids=rows.map(t=>t.id),j=i+delta;if(j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];commit({type:'reorder',blockId:e.blockId,ids}).catch(()=>{});};const up=button('Move up',()=>move(-1),'secondary'),down=button('Move down',()=>move(1),'secondary');up.disabled=i===0;down.disabled=i===rows.length-1;actions.append(up,down);}
  function installOrder(handle,row,e){let start=null,target=null,moved=false,frame=null,point=null;
    const clearMarks=()=>work.querySelectorAll('.drop-target,.drop-active').forEach(n=>n.classList.remove('drop-target','drop-active'));
    const locate=()=>{clearMarks();const hit=document.elementFromPoint(point.x,point.y),zone=hit?.closest('.drop-zone');target=null;if(!zone)return;const other=hit.closest('.task-row'),rows=[...zone.querySelectorAll('.task-row')].filter(n=>Number(n.dataset.taskId)!==e.id);let before=null;if(other&&other!==row){const r=other.getBoundingClientRect(),index=rows.indexOf(other);before=point.y<r.top+r.height/2?other:rows[index+1];}zone.classList.add('drop-active');before?.classList.add('drop-target');target={blockId:zone.dataset.blockId||null,beforeId:before?Number(before.dataset.taskId):null};};
    const tick=()=>{if(!start||!moved)return;const r=work.getBoundingClientRect(),edge=56;let speed=0;if(point.y<r.top+edge)speed=-Math.min(14,(r.top+edge-point.y)/4);else if(point.y>r.bottom-edge)speed=Math.min(14,(point.y-r.bottom+edge)/4);if(speed)work.scrollTop+=speed;locate();frame=requestAnimationFrame(tick);};
    const cleanup=()=>{start=null;cancelAnimationFrame(frame);frame=null;row.classList.remove('dragging');clearMarks();};
    handle.addEventListener('pointerdown',ev=>{ev.stopPropagation();start={x:ev.clientX,y:ev.clientY};point={...start};moved=false;target=null;handle.setPointerCapture(ev.pointerId);});handle.addEventListener('pointermove',ev=>{if(!start)return;point={x:ev.clientX,y:ev.clientY};if(!moved&&Math.hypot(point.x-start.x,point.y-start.y)>7){moved=true;row.classList.add('dragging');tick();}});
    handle.addEventListener('pointerup',ev=>{ev.stopPropagation();const drop=target,wasMoved=moved;cleanup();if(wasMoved&&drop)commit({type:'moveTask',id:e.id,...drop},true).catch(()=>{});});handle.addEventListener('click',ev=>{if(moved){ev.preventDefault();ev.stopImmediatePropagation();moved=false;}},true);handle.addEventListener('pointercancel',cleanup);
  }
  function taskActions(e){focusedTaskId=e.id;focusedBlockId=e.blockId??null;const {body}=openEditor('Task actions');body.append(el('h2','detail-result',e.title),button('Edit task',()=>taskEditor(e.id),'menu-action link'),button('Move to RPM block',()=>movePicker(e),'menu-action link'),button('Change priority',()=>priorityEditor(e),'menu-action link'),button('Ask AI',capture,'menu-action link'),button('Delete task',()=>deleteTask(e),'menu-action danger'));if(e.completions?.length&&repeats(e))body.append(button('Undo last completion',()=>commit({type:'reopenTask',id:e.id}).catch(()=>{}),'menu-action link'));}
  function movePicker(e){const {body}=openEditor('Move task');body.append(el('h2','detail-result',e.title),el('p','muted','Choose its RPM block. Moving keeps the task, its schedule and its details.'));for(const b of [...p().blocks,{id:null,title:'Unsorted'}]){const choice=button(b.title,()=>commit({type:'moveTask',id:e.id,blockId:b.id}).catch(()=>{}),'menu-action link');choice.setAttribute('aria-pressed',String((e.blockId??null)===b.id));body.append(choice);}}
  function deleteTask(e){const {body,actions}=openEditor('Delete task?');body.append(el('h2','detail-result',e.title),el('p','muted','This removes the task from your plan and stops its alerts. You can restore it from Trash in RPM.'));actions.append(button('Keep',()=>taskDetails(e.id),'secondary'),button('Delete task',()=>commit({type:'archiveTask',id:e.id}).then(()=>notice('Moved to Trash',true)).catch(()=>{}),'danger'));}
  function showTrash(){const {body}=openEditor('Trash');const rows=data().entries.filter(e=>e.archived&&(e.kind??'plan')==='plan');if(!rows.length)body.append(el('p','empty','No deleted tasks.'));for(const e of rows){const row=el('div','list-row');row.append(el('span','grow',e.title),button('Restore',()=>commit({type:'restoreTask',id:e.id}).catch(()=>{}),'link'));body.append(row);}}
  function showUnscheduled(){const {body,actions}=openEditor('Unscheduled');const rows=tasks(data()).filter(e=>!e.planned&&!e.done);if(!rows.length)body.append(el('p','empty','Everything with a time is on your day. New captures can stay here until you plan them.'));for(const e of rows)body.append(taskRow(e));actions.append(button('Add task',()=>taskEditor(null),'primary'));}
  function calendarDetails(e){const {body}=openEditor('Calendar commitment');body.append(el('h2','detail-result',e.title),el('p','numeric',`${clock(e.start)} – ${clock(e.end)}`),el('p','read-only','Read-only calendar event. Make changes in your calendar app.'));}
  async function refreshCalendar(){const serial=++calendarSerial;try{const value=await api.native('calendarRead',{anchor:+new Date(day+'T12:00')});if(serial!==calendarSerial)return;calendar=calendarRows(value);calendarState=calendarLabel(value);if(editor.hidden&&level===0)render(false);}catch(e){calendarState='Unavailable';if(editor.hidden&&level===0)render(false);}}
  async function calendarEditor(){const {body,actions}=openEditor('Calendar');body.append(el('p','muted','Read-only calendars already synced on this phone. RPM keeps a limited local copy (3 days back, 22 ahead). It never adds or edits Google events. Sync freshness depends on Android and your calendar account.'));
    try{const result=await api.native('calendarList');if(!body.isConnected)return;if(!result.permitted){body.append(el('p','','Allow read access to choose calendars. Capture and RPM reminders work without it.'));actions.append(button('Allow access',async()=>{try{await api.native('calendarPermission');}catch(e){notice(e.message);}},'primary'),button('Refresh',calendarEditor,'secondary'));return;}
      if(!result.calendars.length)body.append(el('p','empty','No synced calendars found. Add your Google account in Android Settings and enable Calendar sync, then return here.'));
      const rows=result.calendars.map(c=>({id:c.id,input:checkbox(body,c.title+(c.google?' · Google':''),result.selected.includes(c.id))}));actions.append(button('Save selection',async()=>{try{await api.native('calendarSelect',{ids:rows.filter(r=>r.input.checked).map(r=>r.id)});closeEditor();await refreshCalendar();notice('Calendar selection saved');}catch(e){notice(e.message);}},'primary'));
    }catch(e){body.append(el('p','error',e.message));actions.append(button('Retry',calendarEditor,'secondary'));}}
  function openBlock(id){focusedBlockId=id;focusedTaskId=null;rpmFilter=null;level=1;closeEditor();render(true);const section=[...work.querySelectorAll('[data-block-id]')].find(n=>n.dataset.blockId===id);section?.scrollIntoView({block:'start'});}
  function chip(label,selected,action){const b=button(label,action,'chip');b.setAttribute('aria-pressed',String(selected));return b;}
  function projectArea(project){const goal=p().goals.find(g=>g.id===project?.goalId);return p().areas.find(a=>a.id===goal?.areaId);}
  function progressBar(stats,label){const wrap=el('div','progress-block'),line=el('div','row spread');line.append(el('small','muted',label??`${stats.done} of ${stats.total} actions completed`),el('small','accent numeric',stats.total?stats.percent+'%':'—'));const track=el('div','progress-track');track.setAttribute('role','progressbar');track.setAttribute('aria-label',label??'Completed actions');track.setAttribute('aria-valuemin','0');track.setAttribute('aria-valuemax','100');track.setAttribute('aria-valuenow',String(stats.percent));const fill=el('div');fill.style.width=stats.percent+'%';track.append(fill);wrap.append(line,track);return wrap;}
  function renderRPM(){
    const page=el('div','scroll-page rpm-page'),filters=el('div','filter-strip');work.append(page);filters.append(chip('All Blocks',rpmFilter===null,()=>{rpmFilter=null;render(true);}));for(const pr of p().projects)filters.append(chip(pr.title,rpmFilter===pr.id,()=>{rpmFilter=pr.id;render(true);}));filters.append(chip('+ New Block',false,()=>entityEditor('blocks')));page.append(filters);
    const help=el('div','gesture-hint');help.append(el('span','','Swipe right: Complete'),el('span','','Swipe left: Must do'));page.append(help);
    const draft=p().drafts.findLast(d=>d.status==='unreviewed');if(draft){const review=el('div','conflict');review.append(el('p','','AI arrangement · review before accepting.'),button('Accept plan',()=>commit({type:'acceptDraft',id:draft.id},true).catch(()=>{}),'secondary'),button("Don't learn",()=>commit({type:'dismissDraft',id:draft.id},true).catch(()=>{}),'link'));page.append(review);}
    if(!p().blocks.length)page.append(emptyState('Start with a result','Give your actions an outcome and a reason that matters to you.',()=>entityEditor('blocks'),'New RPM block'));
    const blocks=rpmFilter?p().blocks.filter(b=>b.projectId===rpmFilter):[...p().blocks,{id:null,title:'Unsorted'}];
    for(const b of blocks){const section=el('section','rpm-block drop-zone');section.dataset.blockId=b.id??'';section.dataset.tone=toneFor(b.id);section.classList.toggle('focused-block',b.id===focusedBlockId&&!!b.id);section.addEventListener('pointerdown',()=>{focusedBlockId=b.id;focusedTaskId=null;});const project=p().projects.find(pr=>pr.id===b.projectId),rows=blockTasks(data(),b.id),t=totals(rows),only=mustOnly.has(b.id),meta=el('div','row spread block-meta');meta.append(button(project?.title??(b.id?'Independent outcome':'Captured actions'),()=>project?showProject(project.id):b.id?entityEditor('blocks',b.id):showUnscheduled(),'category-chip'));
      const time=button('',()=>{only?mustOnly.delete(b.id):mustOnly.add(b.id);render(false);},'time-toggle');time.setAttribute('aria-label',`${only?'Must do':'All actions'}: ${duration(only?t.must:t.all)}. Toggle must-only view`);time.setAttribute('aria-pressed',String(only));time.append(mark('clock'),el('span','numeric',duration(only?t.must:t.all)));if(only)time.append(el('small','','MUST'));meta.append(time);section.append(meta);
      const heading=el('div','row title-row');heading.append(el('h2','grow',b.title));if(b.id)heading.append(icon('edit','Edit RPM block: '+b.title,()=>entityEditor('blocks',b.id)));section.append(heading);if(b.notes)section.append(el('p','outcome-notes',b.notes));
      if(b.id){const purpose=button('',()=>b.purpose?entityEditor('blocks',b.id):aiAction('purpose',b.id),'purpose-callout');purpose.append(el('small','','Purpose & emotional fuel'),el('p','',b.purpose||'Add your reason for this result'));section.append(purpose);}
      const stats=doneStats(rows),caption=el('div','row spread map-caption');caption.append(el('span','','Massive Action Plan'),el('span','accent',`${stats.done} of ${stats.total} done`));section.append(caption);const list=el('div','task-list');rows.forEach((e,i)=>{if(!only||e.must)list.append(taskRow(e,i));});if(!list.children.length)list.append(el('p','drop-empty',only?'No must-do actions. Tap the time to show all.':'Drop a task here or add one below.'));section.append(list);const summary=el('div','totals');summary.append(el('span','',`Musts ${duration(t.must)}`),el('span','',`All ${duration(t.all)}${t.unknown?' · '+t.unknown+' unestimated':''}`));section.append(summary,button('Add action',()=>taskEditor(null,{blockId:b.id}),'block-add'));page.append(section);}
    const footer=el('div','row');footer.append(button('Sort with AI',()=>aiAction('sort'),'link'),button('Examples',examples,'link'),button('Trash',showTrash,'link'));page.append(footer);
  }
  function showProject(id){projectId=id;projectFilter=null;collapsedProjects.delete(id);closeEditor();level=2;render(true);[...work.querySelectorAll('[data-project-id]')].find(n=>n.dataset.projectId===id)?.scrollIntoView({block:'start'});}
  function renderProjects(){
    const page=el('div','scroll-page projects-page'),filters=el('div','filter-strip');work.append(page);filters.append(chip(`All Outcomes (${p().projects.length})`,projectFilter===null,()=>{projectFilter=null;render(true);}));for(const area of p().areas.filter(a=>p().projects.some(pr=>projectArea(pr)?.id===a.id)))filters.append(chip(area.title,projectFilter===area.id,()=>{projectFilter=area.id;render(true);}));page.append(filters);
    const projects=p().projects.filter(pr=>!projectFilter||projectArea(pr)?.id===projectFilter),blockIds=new Set(p().blocks.filter(b=>projects.some(pr=>pr.id===b.projectId)).map(b=>b.id)),rows=tasks(data()).filter(e=>blockIds.has(e.blockId)),stats=doneStats(rows),summary=el('section','overview-panel'),copy=el('div');copy.append(el('h2','','Multi-Block Outcomes'),el('p','muted small',`${projects.length} projects · ${blockIds.size} RPM blocks`),el('p','accent small',`${stats.done} of ${stats.total} actions completed`));summary.append(copy,progressRing(stats));page.append(summary);
    if(!projects.length)page.append(emptyState('Make room for a bigger outcome','Connect related RPM blocks in a project.',()=>entityEditor('projects'),'New project'));
    for(const pr of projects){const card=el('article','project-card');card.dataset.projectId=pr.id;card.dataset.tone=toneFor(pr.id);card.addEventListener('pointerdown',()=>{projectId=pr.id;focusedTaskId=null;focusedBlockId=null;});const area=projectArea(pr),goal=p().goals.find(g=>g.id===pr.goalId),blocks=p().blocks.filter(b=>b.projectId===pr.id),meta=el('div','row spread');meta.append(el('span','category-chip',area?.title??'Personal project'));if(goal)meta.append(button(String(goal.year),()=>{year=goal.year;lifeFilter=goal.areaId??null;horizon=goal.horizon??'yearly';period=goal.horizon==='quarterly'?(goal.period-1)*3+1:goal.period??period;changeLevel(3);},'goal-link'));card.append(meta);const title=el('div','row title-row');title.append(el('h2','grow',pr.title),icon('edit','Edit project: '+pr.title,()=>{projectId=pr.id;entityEditor('projects',pr.id);}));card.append(title);if(pr.purpose){const purpose=el('p','project-purpose');purpose.append(mark('target'),el('span','',pr.purpose));card.append(purpose);}card.append(progressBar(doneStats(tasks(data()).filter(e=>blocks.some(b=>b.id===e.blockId)))));
      const open=!collapsedProjects.has(pr.id),toggle=button('',()=>{open?collapsedProjects.add(pr.id):collapsedProjects.delete(pr.id);render(false);},'accordion-toggle');toggle.setAttribute('aria-expanded',String(open));toggle.append(mark('layers'),el('span','grow',`RPM Blocks Breakdown (${blocks.length})`),mark(open?'up':'down'));card.append(toggle);const contents=el('div','project-blocks');contents.hidden=!open;for(const b of blocks){const items=blockTasks(data(),b.id),s=doneStats(items),next=items.find(e=>!e.done),entry=button('',()=>openBlock(b.id),'block-summary'),line=el('div','row spread');line.append(el('strong','grow',b.title),el('small','block-count',`${s.done} of ${s.total} done`));entry.append(line,el('small','muted',next?'Next: '+next.title:items.length?'All actions completed':'Add the first action'));contents.append(entry);}if(!blocks.length)contents.append(el('p','muted small','No RPM blocks yet.'));contents.append(button('Add RPM block',()=>{projectId=pr.id;entityEditor('blocks');},'block-add'));card.append(contents);page.append(card);}
  }
  function progressRing(stats){const ring=el('div','progress-ring');ring.style.setProperty('--progress',stats.percent+'%');const inside=el('div');inside.append(el('strong','numeric',stats.total?stats.percent+'%':'—'),el('small','','Completed'));ring.append(inside);return ring;}
  function renderLife(){
    const page=el('div','scroll-page life-page'),tabs=el('div','horizon-tabs');work.append(page);for(const [key,label] of [['yearly','Yearly Vision'],['quarterly','Q'+Math.ceil(period/3)+' Focus'],['monthly','Monthly'],['values','Core Values']])tabs.append(chip(label,horizon===key,()=>{horizon=key;render(true);}));page.append(tabs);
    const periodRow=el('div','row period-row');periodRow.append(icon('back','Previous period',()=>shiftLifePeriod(-1)),el('span','grow numeric',horizon==='monthly'?new Date(year,period-1,1).toLocaleDateString('en',{month:'long',year:'numeric'}):horizon==='quarterly'?`Q${Math.ceil(period/3)} · ${year}`:String(year)),icon('next','Next period',()=>shiftLifePeriod(1)));if(horizon!=='values')page.append(periodRow);
    if(horizon==='values'){const vision=el('section','life-card');vision.append(el('h2','','Core values'),el('p','context-copy',p().context.coreValues||'Keep the principles you want your plans to reflect.'),button('Edit values and vision',contextEditor,'link'));if(p().context.vision)vision.append(el('h3','','Life vision'),el('p','context-copy',p().context.vision));page.append(vision);return;}
    const areas=p().areas,rated=areas.filter(a=>a.rating!=null),selected=areas.find(a=>a.id===lifeFilter),score=selected?.rating??(lifeFilter?null:rated.length?rated.reduce((s,a)=>s+a.rating,0)/rated.length:null),wheel=el('section','wheel-panel'),top=el('div','wheel-top'),copy=el('div','grow');copy.append(button(selected?.title??'Wheel of Life',()=>{lifeFilter=null;render(false);},'wheel-label'),el('h2','wheel-score numeric',score==null?'—':score.toFixed(1)));copy.querySelector('h2').append(el('small','','/10'));copy.append(el('p','accent small',selected?'Your rating':'Your average rating'),el('p','muted small',selected?(selected.purpose||'Tap the area below to update your rating.'):`${rated.length} of ${areas.length} life areas rated`));top.append(copy,lifeWheel(areas));wheel.append(top);const chips=el('div','filter-strip dimension-chips');for(const a of areas){const b=chip(`${a.title} ${a.rating??'—'}`,lifeFilter===a.id,()=>{lifeFilter=lifeFilter===a.id?null:a.id;render(false);});b.dataset.tone=toneFor(a.id);chips.append(b);}wheel.append(chips);if(!areas.length)wheel.append(button('Add your first life area',areaPicker,'link'));page.append(wheel);
    const heading=el('div','row spread life-section-heading');heading.append(el('h2','','Core Life Categories'),icon('plus','New life area',()=>entityEditor('areas')));page.append(heading);
    const goals=p().goals.filter(g=>g.year===year&&(g.horizon??'yearly')===horizon&&(horizon==='yearly'||g.period===(horizon==='monthly'?period:Math.ceil(period/3))));
    for(const area of [...areas,{id:null,title:'Unassigned'}]){if(lifeFilter&&area.id!==lifeFilter)continue;const grouped=goals.filter(g=>(g.areaId??null)===area.id);if(!area.id&&!grouped.length)continue;const card=el('section','life-card');card.dataset.tone=toneFor(area.id);const title=button('',()=>{collapsedAreas.has(area.id)?collapsedAreas.delete(area.id):collapsedAreas.add(area.id);render(false);},'area-heading');title.setAttribute('aria-expanded',String(!collapsedAreas.has(area.id)));title.append(mark('life'),el('h3','grow',area.title),el('span','area-score numeric',area.rating==null?'—':area.rating+'/10'),mark(collapsedAreas.has(area.id)?'down':'up'));card.append(title);const content=el('div','area-content');content.hidden=collapsedAreas.has(area.id);if(area.purpose)content.append(el('p','area-purpose',area.purpose));if(area.id)content.append(button(area.rating==null?'Rate this life area':'Edit area & rating',()=>entityEditor('areas',area.id),'link small'));
      for(const g of grouped){const goal=button('',()=>entityEditor('goals',g.id),'goal-item');goal.append(el('span','goal-period',horizon==='yearly'?String(g.year):horizon==='quarterly'?'Q'+g.period:new Date(g.year,g.period-1).toLocaleDateString('en',{month:'short'})),el('span','grow',g.title),mark('next'));content.append(goal);if(g.purpose)content.append(el('p','goal-purpose',g.purpose));for(const pr of p().projects.filter(pr=>pr.goalId===g.id))content.append(button(pr.title,()=>showProject(pr.id),'linked-project'));}
      if(!grouped.length)content.append(el('p','muted small','No goals in this period yet.'));content.append(button('Add goal',()=>entityEditor('goals',null,{areaId:area.id}),'block-add'));card.append(content);page.append(card);}
    if(!areas.length&&!goals.length)page.append(emptyState('What matters to you?','Create a life area, then add a goal for this period.',()=>entityEditor('areas'),'New life area'));
    const tools=el('div','row');tools.append(button('Goal ideas',()=>aiAction('ideas'),'link'),button('Goals and vision',contextEditor,'link'));page.append(tools);
  }
  function lifeWheel(areas){const svg=svgNode('svg',{viewBox:'0 0 140 140',class:'life-wheel',role:'img','aria-label':areas.length?'Life area ratings. '+areas.map(a=>a.title+': '+(a.rating??'unrated')).join(', '):'Add life areas to create your wheel'}),n=Math.max(3,areas.length),point=(i,r)=>[70+Math.sin(i/n*Math.PI*2)*r,70-Math.cos(i/n*Math.PI*2)*r],points=r=>Array.from({length:n},(_,i)=>point(i,r).join(',')).join(' ');for(const r of [16,32,48])svg.append(svgNode('polygon',{points:points(r),class:'wheel-grid'}));areas.forEach((a,i)=>{const [x,y]=point(i,48);svg.append(svgNode('line',{x1:70,y1:70,x2:x,y2:y,class:'wheel-spoke'}));});if(areas.length>=3&&areas.every(a=>a.rating!=null))svg.append(svgNode('polygon',{points:areas.map((a,i)=>point(i,a.rating/10*48).join(',')).join(' '),class:'wheel-value'}));areas.forEach((a,i)=>{if(a.rating==null)return;const [x,y]=point(i,a.rating/10*48);svg.append(svgNode('circle',{cx:x,cy:y,r:lifeFilter===a.id?5:3,class:'wheel-node','data-tone':toneFor(a.id)}));});return svg;}
  function entityEditor(collection,id=null,defaults={}){
    const names={projects:'project',blocks:'RPM block',areas:'life area',goals:'goal'},r=id?p()[collection].find(x=>x.id===id):defaults;if(!r)return;
    const {body,actions}=openEditor((id?'Edit ':'New ')+names[collection],collection+':'+(id??'new'));
    const name=field(body,collection==='blocks'?'Result / outcome':'Title',r.title),purpose=field(body,'Purpose · why this matters',r.purpose,'textarea');let parent,goalYear,goalHorizon,goalPeriod,rating;
    if(collection==='blocks')parent=select(body,'Project',r.projectId??projectId,[['','Unassigned'],...p().projects.map(pr=>[pr.id,pr.title])]);
    if(collection==='projects')parent=select(body,'Goal',r.goalId,[['','Unassigned'],...p().goals.map(g=>[g.id,`${g.year} · ${g.title}`])]);
    if(collection==='areas'){rating=field(body,'Your rating · 0 to 10, optional',r.rating??'','number');rating.min='0';rating.max='10';rating.step='0.1';body.append(el('p','muted small','Your own reflection on this area, independent of task completion.'));}
    if(collection==='goals'){
      goalYear=field(body,'Year',r.year??year,'number');goalYear.min=2000;goalYear.max=2200;
      parent=select(body,'Life area',r.areaId??lifeFilter,[['','Unassigned'],...p().areas.map(a=>[a.id,a.title])]);
      goalHorizon=select(body,'Horizon',r.horizon??(id?'yearly':horizon==='values'?'yearly':horizon),[['yearly','Yearly vision'],['quarterly','Quarterly focus'],['monthly','Monthly']]);
      goalPeriod=select(body,'Period',String(r.period??(goalHorizon.value==='quarterly'?Math.ceil(period/3):period)),[]);
      const updatePeriods=(initial=false)=>{const current=initial?(draftValues.Period??r.period??(goalHorizon.value==='quarterly'?Math.ceil(period/3):period)):Number(goalPeriod.value)||1;goalPeriod.replaceChildren();const count=goalHorizon.value==='quarterly'?4:12;for(let i=1;i<=count;i++){const o=el('option','',goalHorizon.value==='quarterly'?'Quarter '+i:new Date(2000,i-1).toLocaleDateString('en',{month:'long'}));o.value=String(i);goalPeriod.append(o);}goalPeriod.value=String(Math.min(count,current));goalPeriod.parentElement.hidden=goalHorizon.value==='yearly';};updatePeriods(true);goalHorizon.addEventListener('change',()=>updatePeriods());
    }
    const notes=field(body,'Notes',r.notes,'textarea'),err=el('p','edit-error error');body.append(err);
    if(id)body.append(button('Remove '+names[collection],()=>{const confirm=el('div','conflict');confirm.append(el('p','',`Remove this ${names[collection]}? Its contents will be kept unassigned. You can undo.`),button('Keep',()=>confirm.remove()),button('Remove',()=>commit({type:'removeEntity',collection,id}).catch(()=>{}),'danger'));body.append(confirm);confirm.scrollIntoView({block:'nearest'});},'danger'));
    actions.append(button('Cancel',()=>{discardDraft();closeEditor();}),button('Save',async()=>{try{const fields={title:name.value,purpose:purpose.value,notes:notes.value};if(collection==='blocks')fields.projectId=parent.value||null;if(collection==='projects')fields.goalId=parent.value||null;if(collection==='areas')fields.rating=rating.value===''?null:Number(rating.value);if(collection==='goals'){fields.areaId=parent.value||null;fields.year=Number(goalYear.value);fields.horizon=goalHorizon.value;fields.period=goalHorizon.value==='yearly'?null:Number(goalPeriod.value);}const saved=await commit({type:'saveEntity',collection,id,fields});if(collection==='projects'){projectId=saved;collapsedProjects.delete(saved);render(true);}if(collection==='goals'){year=fields.year;horizon=fields.horizon;if(horizon!=='yearly')period=horizon==='quarterly'?(fields.period-1)*3+1:fields.period;render(true);}}catch(e){err.textContent=e.message;}},'primary'));
  }
  function projectPicker(){const {body,actions}=openEditor('Projects');for(const pr of p().projects){const row=el('div','list-row');row.append(button(pr.title,()=>{projectId=pr.id;level=2;closeEditor();render(true);},'grow link'),button('Edit',()=>entityEditor('projects',pr.id),'link'));body.append(row);}body.append(button('All RPM blocks',()=>{level=1;closeEditor();render(true);},'link'));actions.append(button('New project',()=>entityEditor('projects'),'primary'));}
  function areaPicker(){const {body,actions}=openEditor('Life areas');for(const a of p().areas)body.append(button(a.title,()=>entityEditor('areas',a.id),'link'));if(!p().areas.length)body.append(el('p','empty','Choose your own life areas—for example, relationships or learning. These are examples, not a preset profile.'));actions.append(button('New area',()=>entityEditor('areas'),'primary'));}
  async function aiAction(action,blockId=null){const startVersion=data().version,{body,actions}=openEditor(action==='sort'?'Sort into RPM blocks':action==='purpose'?'Purpose suggestion':'Goal ideas');const status=el('p','muted','Preparing a suggestion…');status.setAttribute('role','status');body.append(status);if(!api.getPhone().hasKey){status.textContent='Connect your AI key in Settings to get suggestions. Your plans stay saved.';actions.append(button('Settings',()=>api.native('settings'),'primary'));return;}
    try{const request=planningRequest(data(),action,blockId);if(action==='sort'&&!JSON.parse(request.messages[1].content).context.tasks.length){status.textContent='No unsorted active tasks to arrange. You can move tasks manually or capture something new.';return;}const response=await api.native('model',{body:request});if(response.status<200||response.status>=300)throw new Error('The AI request failed. Check your connection and try again.');const result=readPlanningResponse(response.body,action);if(data().version!==startVersion)throw new Error('Your plans changed while the AI was working. Ask again for a fresh suggestion.');if(!body.isConnected)return;status.textContent=action==='sort'?(result.explanation??'Proposed arrangement. Nothing has moved yet.'):result.text;
      if(action==='sort'){for(const b of result.blocks){const section=el('section','detail-section');section.append(el('h3','',b.title));for(const id of b.taskIds??[])section.append(el('p','',tasks(data()).find(e=>e.id===id)?.title??'Unknown task'));body.append(section);}actions.append(button('Apply draft',async()=>{try{if(data().version!==startVersion)throw new Error('Your plans changed. Ask for a new draft.');await commit({type:'aiDraft',blocks:result.blocks});level=1;const b=p().blocks.find(x=>x.id===p().drafts.at(-1)?.blockIds[0]);projectId=b?.projectId??null;render(true);}catch(e){notice(e.message);}},'primary'));}
      if(action==='purpose'){const b=p().blocks.find(x=>x.id===blockId);actions.append(button('Use purpose',()=>commit({type:'saveEntity',collection:'blocks',id:blockId,fields:{...b,purpose:result.text}}).catch(()=>{}),'primary'));}
    }catch(e){if(body.isConnected){status.textContent=e.message;status.className='error';}}
  }
  function contextEditor(){const {body,actions}=openEditor('Goals and vision','context');body.append(el('p','muted','Only reviewed text is used for purpose and goal ideas. Sorting does not receive these documents.'));const vision=field(body,'Life vision',p().context.vision,'textarea'),goals=field(body,'Goals and interests',p().context.goals,'textarea'),values=field(body,'Core values',p().context.coreValues,'textarea'),approved=checkbox(body,'I reviewed this context; use it for suggestions',p().context.approved);body.append(el('p','edit-error error'));actions.append(button('Save',()=>commit({type:'context',vision:vision.value,goals:goals.value,coreValues:values.value,approved:approved.checked}).catch(()=>{}),'primary'));}
  function examples(){const {body}=openEditor('Example RPM blocks');body.append(el('p','muted','Illustrations only. These are not saved goals or assumptions about you.'));for(const [r,why,actions] of [['Explain a chapter clearly','Feel prepared to contribute','Read key sections; write three points; discuss one question'],['Have the home ready for the week','Make everyday life easier','Buy essentials; prepare meals; clear the workspace']]){const s=el('section','detail-section');s.append(el('h2','detail-result',r),el('p','',why),el('p','muted',actions));body.append(s);}}
  window.rpmHandleBack=()=>{if(!editor.hidden){closeEditor();return true;}if(level>0){changeLevel(level-1);return true;}return false;};
  window.addEventListener('rpm-data-refresh',()=>{if(editor.hidden)render(false);else notice('Saved data changed. Review before saving.');});
  window.addEventListener('rpm-phone-status',refreshCalendar);
  projectId=p().projects[0]?.id??null;p().projects.slice(1).forEach(pr=>collapsedProjects.add(pr.id));swipe(work);swipe($('planner-tabs'),true);render(true);refreshCalendar();
  editor.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeEditor();}if(e.key==='Tab'){const nodes=[...editor.querySelectorAll('button,input,select,textarea,[tabindex="0"]')].filter(n=>!n.disabled&&n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
  function openView(target){if(typeof target.id==='number'){taskDetails(target.id);return;}if(target.view==='ideas'){aiAction('ideas');return;}if(target.view==='vision'){contextEditor();return;}if(target.view==='calendar'){calendarEditor();return;}if(target.view==='rpm'&&target.id){openBlock(target.id);return;}if(target.view==='projects'&&target.id){showProject(target.id);return;}if(target.view==='life'&&target.id){const goal=p().goals.find(g=>g.id===target.id);if(goal){year=goal.year;lifeFilter=goal.areaId??null;horizon=goal.horizon??'yearly';period=goal.horizon==='quarterly'?(goal.period-1)*3+1:goal.period??period;collapsedAreas.delete(goal.areaId);}}if(target.view==='day'&&/^\d{4}-\d{2}-\d{2}$/.test(target.date??''))day=target.date;const next=['day','rpm','projects','life'].indexOf(target.view);if(next>=0){level=next;render(true);}}
  return {render,taskEditor,goalIdeas:()=>aiAction('ideas'),contextEditor,openView};
}
