import test from 'node:test';import assert from 'node:assert/strict';
import {createCompanionAgent,MODEL} from '../chat-prototype/companion-agent.mjs';
import {freshStore} from '../chat-prototype/companion-state.mjs';
import {propose,undo} from '../chat-prototype/companion-tools.mjs';
import {createPlannerTools,changePlanner,plannerSummary,readPlanner,plannerInstruction} from './planner-tools.mjs';
import {phoneProposal} from './planner-chat.mjs';
import {editPlan,blockTasks} from './planner-state.mjs';
test('capture focus retains selected day and invalid entity IDs never become a target',()=>{const d=freshStore(),s=plannerSummary(d,{day:'2026-09-16',view:'projects',projectId:'missing'});assert.equal(s.focus.date,'2026-09-16');assert.equal(s.focus.project,null);});
const raw='Create a Study project, an Exam readiness RPM block, and add Read chapter one to it.';
const op=(collection,fields,id=null,type='create',ref=null)=>({collection,fields,id,type,ref,evidence:[raw]});
const args=operations=>({operations,continuation:false,question:null,choices:[]});
const meta=d=>({raw,conversationId:d.conversations[0].id,now:new Date(2026,8,16,8)});
const create=()=>args([op('projects',{title:'Study'},null,'create','p'),op('blocks',{title:'Exam readiness',projectId:'$p'},null,'create','b'),op('tasks',{title:'Read chapter one',blockId:'$b'})]);
test('date-only capture retains the chosen day without manufacturing a clock',async()=>{const d=freshStore();await changePlanner(d,args([op('tasks',{title:'Read',time:'tomorrow'})]),meta(d));assert.equal(d.entries[0].planned,null);assert.equal(d.entries[0].plannedDate,'2026-09-17');});
const staleDayCorrections=[
 {via:'changePlanner',seed:d=>{editPlan(d,{type:'saveTask',fields:{title:'Meeting',planned:'2026-09-17T03:30:00.000Z'}});d.entries[0].plannedDate='2026-09-17';},
  correct:(d,raw,now)=>changePlanner(d,{operations:[{...op('tasks',{time:'9:15 am'},1,'update'),evidence:[raw]}],continuation:false,question:null,choices:[]},{raw,conversationId:d.conversations[0].id,now}),when:r=>r.plannerReceipts[0].entry.when,plannedDate:null},
 {via:'legacy propose',seed:d=>{const created='Give cash tomorrow at 8pm';propose(d,{operations:[{type:'create',id:null,fields:{title:'Give cash',time:'tomorrow at 8pm',alert:'reminder'},evidence:[created],collection:'entries'}],continuation:false,question:null,choices:[]},{raw:created,conversationId:d.conversations[0].id,now:new Date('2026-09-16T08:00:00+05:30')});},
  correct:(d,raw,now)=>propose(d,{operations:[{type:'update',id:1,fields:{time:'9:15am',alert:'alarm'},evidence:[raw],collection:'entries'}],continuation:false,question:null,choices:[]},{raw,conversationId:d.conversations[0].id,now}),when:r=>r.receipts[0].when,plannedDate:'2026-09-18'}
];
for(const c of staleDayCorrections)test(`clock correction after a stale saved day uses the next future occurrence (${c.via})`,async()=>{
 const d=freshStore();c.seed(d);assert.equal(d.entries[0].plannedDate,'2026-09-17');
 const r=await c.correct(d,'No, make it 915 am',new Date('2026-09-18T07:54:00+05:30'));
 assert.equal(d.entries[0].planned,'2026-09-18T03:45:00.000Z');assert.equal(d.entries[0].plannedDate,c.plannedDate);assert.equal(d.pending,null);assert.match(c.when(r),/9:15 AM/);
});
test('a concrete new task saves while an older proposal remains available',async()=>{const d=freshStore(),old=args([op('tasks',{title:'Meeting',time:'9'},null,'create')]);old.question='9 AM or 9 PM?';await changePlanner(d,old,meta(d));const savedPending=structuredClone(d.pending),requestRaw='Add buy milk';const request={operations:[{collection:'tasks',fields:{title:'Buy milk'},id:null,type:'create',ref:null,evidence:[requestRaw]}],continuation:false,question:null,choices:[]};await changePlanner(d,request,{raw:requestRaw,conversationId:d.conversations[0].id,now:new Date(2026,8,16,8)});assert.equal(d.entries.at(-1).title,'Buy milk');assert.deepEqual(d.pending,savedPending);});
test('a concrete new task also preserves a legacy kindless proposal',async()=>{const d=freshStore(),created='Give cash tomorrow at 8pm';propose(d,{operations:[{type:'create',id:null,fields:{title:'Give cash',time:'tomorrow at 8pm'},evidence:[created],collection:'entries'}],continuation:false,question:null,choices:[]},{raw:created,conversationId:d.conversations[0].id,now:new Date('2026-09-16T08:00:00+05:30')});const correction='Give cash alarm 915',operation={type:'update',id:1,fields:{time:'9:15pm',alert:'alarm'},evidence:[correction],collection:'entries'};propose(d,{operations:[operation],continuation:false,question:'What future time?',choices:[]},{raw:correction,conversationId:d.conversations[0].id,now:new Date('2026-09-18T07:54:00+05:30')});assert.equal(d.pending.kind,undefined);const savedPending=structuredClone(d.pending),requestRaw='Just add Buy milk as a task',request={operations:[{collection:'tasks',fields:{title:'Buy milk'},id:null,type:'create',ref:null,evidence:[requestRaw]}],continuation:false,question:null,choices:[]};await changePlanner(d,request,{raw:requestRaw,conversationId:d.conversations[0].id,now:new Date('2026-09-20T10:17:00+05:30')});assert.equal(d.entries.at(-1).title,'Buy milk');assert.deepEqual(d.pending,savedPending);});
test('manual editor and AI priority edits normalize destination and source order',()=>{const d=freshStore(),a=editPlan(d,{type:'saveEntity',collection:'blocks',fields:{title:'A'}}),b=editPlan(d,{type:'saveEntity',collection:'blocks',fields:{title:'B'}});for(let i=0;i<3;i++)editPlan(d,{type:'saveTask',fields:{title:'Task '+i,blockId:a}});editPlan(d,{type:'saveTask',id:3,fields:{priority:1}});assert.deepEqual(blockTasks(d,a).map(e=>e.id),[3,1,2]);editPlan(d,{type:'saveTask',id:1,fields:{blockId:b}});assert.deepEqual(blockTasks(d,a).map(e=>e.priority),[1,2]);assert.equal(blockTasks(d,b)[0].priority,1);});
test('real capture agent creates linked project block task through the app tool registry',async()=>{
 const d=freshStore();let request;
 const agent=createCompanionAgent({apiKey:'fixture',platform:'android',appTools:createPlannerTools(),appContext:plannerSummary,appInstruction:plannerInstruction,fetchImpl:async(_,o)=>{request=JSON.parse(o.body);return {ok:true,json:async()=>({model:MODEL,choices:[{finish_reason:'tool_calls',message:{tool_calls:[{id:'c',type:'function',function:{name:'change_planner',arguments:JSON.stringify(create())}}]}}]})};}});
 const r=await agent(d,raw,meta(d));assert.equal(r.error,undefined);assert.ok(request.tools.some(t=>t.function.name==='read_planner'));assert.equal(d.entries[0].blockId,d.planner.blocks[0].id);assert.equal(d.planner.blocks[0].projectId,d.planner.projects[0].id);assert.equal(d.entries[0].raw,raw);
 assert.equal(r.text,'Saved.');assert.equal(r.suggestions.length,0);assert.deepEqual(r.plannerReceipts.map(x=>[x.collection,x.id]),[['projects',d.planner.projects[0].id],['blocks',d.planner.blocks[0].id],['tasks',d.entries[0].id]]);assert.equal(r.plannerReceipts[2].entry.raw,raw);
});
test('invalid compound reference never partially creates records',async()=>{const d=freshStore(),before=structuredClone(d),a=create();a.operations[2].fields.blockId='$missing';await assert.rejects(changePlanner(d,a,meta(d)),/reference/);assert.deepEqual(d,before);});
test('sparse entity edits preserve purpose and parent linkage',async()=>{const d=freshStore();await changePlanner(d,create(),meta(d));const b=d.planner.blocks[0];await changePlanner(d,args([op('blocks',{purpose:'Contribute confidently'},b.id,'update')]),meta(d));assert.equal(d.planner.blocks[0].title,'Exam readiness');assert.equal(d.planner.blocks[0].projectId,b.projectId);});
test('question holds complete hierarchy and continuation preserves all operations',async()=>{const d=freshStore(),a=create();a.question='Which chapter?';await changePlanner(d,a,meta(d));assert.equal(d.entries.length,0);assert.equal(d.planner,undefined);await assert.rejects(changePlanner(d,{...create(),operations:create().operations.slice(0,1),continuation:true},meta(d)),/every operation/);await changePlanner(d,{...create(),continuation:true},meta(d));assert.equal(d.entries.length,1);});
test('delete task is recoverable and undo restores the complete planner transaction',async()=>{const d=freshStore();await changePlanner(d,create(),meta(d));const before=structuredClone(d.planner.blocks);const r=await changePlanner(d,args([op('tasks',{},1,'delete'),op('blocks',{},d.planner.blocks[0].id,'delete')]),meta(d));assert.equal(d.entries[0].archived,true);assert.equal(d.planner.blocks.length,0);undo(d,r.undoId);assert.equal(d.entries[0].archived,false);assert.deepEqual(d.planner.blocks,before);});
test('task move updates both block orders and restores as one undo',()=>{const d=freshStore();const a=editPlan(d,{type:'saveEntity',collection:'blocks',fields:{title:'A'}}),b=editPlan(d,{type:'saveEntity',collection:'blocks',fields:{title:'B'}});for(let i=0;i<3;i++)editPlan(d,{type:'saveTask',fields:{title:'Task '+i,blockId:i<2?a:b,priority:i+1}});editPlan(d,{type:'moveTask',id:1,blockId:b,beforeId:3});assert.deepEqual(blockTasks(d,b).map(e=>e.id),[1,3]);assert.equal(blockTasks(d,a)[0].priority,1);editPlan(d,{type:'undo'});assert.deepEqual(blockTasks(d,a).map(e=>e.id),[1,2]);});
test('scoped planner context excludes raw chats and unreviewed life documents',async()=>{const d=freshStore();await changePlanner(d,create(),meta(d));d.planner.context.vision='PRIVATE_VISION';d.conversations[0].messages=[{text:'PRIVATE_CHAT'}];const s=plannerSummary(d,{blockId:d.planner.blocks[0].id});assert.equal(s.focus.project.title,'Study');assert.ok(!JSON.stringify(s).includes('PRIVATE'));assert.equal(readPlanner(d,{collection:'blocks',query:'Exam',cursor:0}).items[0].id,d.planner.blocks[0].id);});
test('planner chat uses calendar checks and explicit rechecked conflict override',async()=>{const d=freshStore(),a=args([op('tasks',{title:'Read',time:'today at 10am'})]),calendar=async()=>({status:'ready',start:+new Date(2026,8,13),end:+new Date(2026,9,8),events:[{id:'meeting',title:'Meeting',start:+new Date(2026,8,16,10),end:+new Date(2026,8,16,11)}]});await changePlanner(d,a,meta(d),calendar);assert.equal(d.entries.length,0);assert.equal(d.pending.kind,'planner');await changePlanner(d,{...a,continuation:true},{...meta(d),raw:'Save anyway'},calendar);assert.equal(d.entries.length,1);});
test('recurring completion and reopen through shared commands preserve the series',async()=>{const d=freshStore();await changePlanner(d,args([op('tasks',{title:'Read',time:'today at 10am',recurrence:'daily'})]),meta(d));await changePlanner(d,args([op('tasks',{},1,'complete')]),meta(d));assert.equal(d.entries[0].done,false);assert.equal(d.entries[0].completedOccurrences.length,1);await changePlanner(d,args([op('tasks',{},1,'reopen')]),meta(d));assert.equal(d.entries[0].completedOccurrences.length,0);});
test('malformed multi-call replies are repaired without executing a partial transaction',async()=>{const data=freshStore();let count=0;const call={id:'one',type:'function',function:{name:'respond',arguments:JSON.stringify({message:'No changes requested.',suggestions:[]})}};const agent=createCompanionAgent({apiKey:'fixture',fetchImpl:async(_,o)=>{assert.equal(JSON.parse(o.body).parallel_tool_calls,undefined);return {ok:true,json:async()=>({model:MODEL,choices:[{finish_reason:'tool_calls',message:{tool_calls:++count===1?[call,{...call,id:'two'}]:[call]}}]})};}});const r=await agent(data,'Hello',{conversationId:data.conversations[0].id});assert.equal(r.error,undefined);assert.equal(count,2);assert.equal(data.entries.length,0);});
test('parallel planner reads can precede one atomic change',async()=>{const d=freshStore();let requests=0,reads=0;const read={name:'read_planner',schema:{type:'object',properties:{},required:[],additionalProperties:false},run:()=>{reads++;return {items:[]};}},call=id=>({id,type:'function',function:{name:'read_planner',arguments:'{}'}});const agent=createCompanionAgent({apiKey:'fixture',appTools:[read],fetchImpl:async()=>({ok:true,json:async()=>({model:MODEL,choices:[{finish_reason:'tool_calls',message:{tool_calls:++requests===1?[call('a'),call('b')]:[{id:'c',type:'function',function:{name:'respond',arguments:JSON.stringify({message:'Read the current plans.',suggestions:[]})}}]}}]})})});const r=await agent(d,'What is planned?',{conversationId:d.conversations[0].id});assert.equal(r.error,undefined);assert.equal(reads,2);assert.equal(requests,2);assert.equal(d.entries.length,0);});
test('android respond binds a goal suggestion to the exact current message',async()=>{
 const data=freshStore(),raw='I want to learn more about cognitive load and context shifting and its effects, and see how Twitter, WhatsApp, and the missing deep focus hours are affecting me.';
 let request;
 const agent=createCompanionAgent({apiKey:'fixture',platform:'android',fetchImpl:async(_,options)=>{request=JSON.parse(options.body);return {ok:true,json:async()=>({model:MODEL,choices:[{finish_reason:'tool_calls',message:{tool_calls:[{id:'goal',type:'function',function:{name:'respond',arguments:JSON.stringify({message:'That could be held as a goal.',suggestions:[{label:'A goal?',text:'Turn this thought into a goal.',action:'goal_draft',title:'Understand how context shifting affects my deep focus'}]})}}]}}]})};}});
 const result=await agent(data,raw,{conversationId:data.conversations[0].id,now:new Date(2026,8,16)});
 const schema=request.tools.find(t=>t.function.name==='respond').function.parameters.properties.suggestions.items;
 assert.deepEqual(schema.required,['label','text']);assert.ok(schema.properties.action.enum.includes('goal_draft'));
 assert.equal(result.suggestions[0].captureAction.draft.sourceRaw,raw);assert.equal(result.suggestions[0].captureAction.draft.title,'Understand how context shifting affects my deep focus');assert.equal(data.planner,undefined);
});
test('upgrading keeps an unfinished legacy capture proposal continuable with planner tools present',async()=>{
 const data=freshStore(),now=new Date(2026,8,12,8),conversationId=data.conversations[0].id,readCalendar=async()=>({status:'not_selected',events:[]});
 const operations=[{type:'create',collection:'entries',id:null,fields:{title:'Walk',kind:'plan',time:null},evidence:['Walk at 10']}];
 await phoneProposal(data,{operations,continuation:false,question:'10 AM or 10 PM?',choices:[{label:'AM',text:'10am'},{label:'PM',text:'10pm'}]},{raw:'Walk at 10',now,conversationId},readCalendar);
 assert.equal(data.pending.kind,undefined);assert.equal(data.entries.length,0);
 const args={operations:[{...operations[0],fields:{...operations[0].fields,time:'10am'}}],continuation:true,question:null,choices:[]};
 const agent=createCompanionAgent({apiKey:'fixture',platform:'android',appTools:createPlannerTools({readCalendar}),appInstruction:plannerInstruction,proposeImpl:(d,a,m)=>phoneProposal(d,a,m,readCalendar),fetchImpl:async(_,options)=>{
   const body=JSON.parse(options.body);assert.match(body.messages[0].content,/legacy pending proposal with no kind field/);assert.ok(body.tools.some(t=>t.function.name==='change_planner'));
   return {ok:true,json:async()=>({model:MODEL,choices:[{finish_reason:'tool_calls',message:{tool_calls:[{id:'legacy',type:'function',function:{name:'propose_changes',arguments:JSON.stringify(args)}}]}}]})};
 }});
 const result=await agent(data,'10am',{now,conversationId});assert.equal(result.error,undefined);assert.equal(data.pending,null);assert.equal(data.entries.length,1);assert.equal(data.entries[0].title,'Walk');assert.equal(new Date(data.entries[0].planned).getHours(),10);
});
