import test from 'node:test';
import assert from 'node:assert/strict';
import {freshStore} from '../chat-prototype/companion-state.mjs';
import {editPlan,blockTasks,localDay} from './planner-state.mjs';
import {migratePlannerUX,dayTasks,taskContext,reorderTask,areaTone} from './planner-ux.mjs';

function fixture(){const d=freshStore();const area=editPlan(d,{type:'saveEntity',collection:'areas',fields:{title:'Learning'}});const goal=editPlan(d,{type:'saveEntity',collection:'goals',fields:{title:'Understand',areaId:area,year:2026}});const project=editPlan(d,{type:'saveEntity',collection:'projects',fields:{title:'Term',goalId:goal}});const block=editPlan(d,{type:'saveEntity',collection:'blocks',fields:{title:'Explain the chapter',purpose:'Contribute with confidence',projectId:project}});return {d,area,goal,project,block};}
test('migration is lossless and idempotent across archived tasks and Undo',()=>{const {d,block}=fixture();const id=editPlan(d,{type:'saveTask',fields:{title:'Read',blockId:block,purpose:'My exact reason',notes:'Original note'}});const second=editPlan(d,{type:'saveTask',fields:{title:'Unassigned',purpose:'Keep this Why'}});d.entries[0].purpose='My exact reason';d.entries[0].notes='Original note';d.planner.undo.entries[0].purpose='My exact reason';d.planner.undo.entries[0].notes='Original note';d.entries[0].starred=true;d.entries[0].archived=true;const raw=d.entries.map(t=>t.raw),snapshot=structuredClone(d);assert.equal(migratePlannerUX(d),true);assert.equal(d.entries[0].must,true);assert.equal(d.entries[0].purpose,'');assert.equal(d.entries[0].notes,'Original note\n\nPrevious task purpose: My exact reason');assert.equal(d.entries[1].purpose,'Keep this Why');assert.deepEqual(d.entries.map(t=>t.raw),raw);assert.equal(d.entries[0].revisions.at(-1).before.purpose,snapshot.entries[0].purpose);const once=JSON.stringify(d);assert.equal(migratePlannerUX(d),false);assert.equal(JSON.stringify(d),once);editPlan(d,{type:'undo'});assert.equal(d.entries[0].purpose,'');assert.ok(d.entries[0].notes.includes('My exact reason'));});
test('legacy equal priorities sort by time and unassigned stars become Must',()=>{const {d}=fixture();d.entries=[{id:1,title:'Late',raw:'Late',priority:1,planned:'2026-09-26T15:00:00Z',star:true},{id:2,title:'Early',raw:'Early',priority:1,planned:'2026-09-26T09:00:00Z'},{id:3,title:'Anytime',raw:'Anytime',mustDo:true}];migratePlannerUX(d);assert.deepEqual(blockTasks(d,null).map(t=>t.id),[2,1,3]);assert.equal(d.entries[0].must,true);assert.equal(d.entries[2].must,true);});
test('Today includes dated Must tasks, overdue dated Musts and linked Result without assigning undated tasks',()=>{const {d,block}=fixture(),today=localDay();const current=editPlan(d,{type:'saveTask',fields:{title:'Current',blockId:block,planned:new Date(Date.now()-60000).toISOString(),minutes:30}});const due=editPlan(d,{type:'saveTask',fields:{title:'Must anytime',plannedDate:today,must:true}});const backlog=editPlan(d,{type:'saveTask',fields:{title:'Yesterday Must',plannedDate:'2020-01-01',must:true}});const undated=editPlan(d,{type:'saveTask',fields:{title:'No invented day',must:true}});const day=dayTasks(d,today);assert.deepEqual(new Set(day.active.map(t=>t.id)),new Set([current,due,backlog]));assert.equal(day.focus.id,current);assert.equal(taskContext(d,day.focus).purpose,'Contribute with confidence');assert.equal(day.active.some(t=>t.id===undated),false);});
test('completion and Undo preserve the Result and order; drag changes no schedule',()=>{const {d,block}=fixture();const ids=['One','Two','Three'].map(title=>editPlan(d,{type:'saveTask',fields:{title,blockId:block,planned:'2026-09-27T10:00:00Z'}}));const order=reorderTask(ids,ids[0],ids[2]);editPlan(d,{type:'reorder',blockId:block,ids:order});assert.deepEqual(blockTasks(d,block).map(t=>t.id),[ids[1],ids[2],ids[0]]);assert.ok(d.entries.every(t=>t.planned==='2026-09-27T10:00:00Z'));editPlan(d,{type:'saveTask',id:ids[0],fields:{done:true}});assert.equal(d.planner.blocks[0].achieved,undefined);editPlan(d,{type:'undo'});assert.equal(d.entries[0].done,false);assert.deepEqual(blockTasks(d,block).map(t=>t.id),order);});
test('half-step rating update is atomic, Undo-able, and preserves old fractional ratings until edited',()=>{const {d,area}=fixture();d.planner.areas[0].rating=8.2;migratePlannerUX(d);assert.equal(d.planner.areas[0].rating,8.2);assert.throws(()=>editPlan(d,{type:'rateAreas',ratings:[{id:area,rating:6.5},{id:area,rating:1.2}]}));assert.equal(d.planner.areas[0].rating,8.2);editPlan(d,{type:'rateAreas',ratings:[{id:area,rating:6.5}]});assert.equal(d.planner.areas[0].rating,6.5);editPlan(d,{type:'undo'});assert.equal(d.planner.areas[0].rating,8.2);assert.equal(areaTone(d.planner.areas[0],d.planner.areas),'area-0');});
test('tomorrow just after midnight never appears in today or today dots',()=>{const {d}=fixture();const when=new Date();when.setDate(when.getDate()+1);when.setHours(0,15,0,0);editPlan(d,{type:'saveTask',fields:{title:'Tomorrow',planned:when.toISOString()}});assert.equal(dayTasks(d,localDay()).active.length,0);assert.equal(dayTasks(d,localDay(when)).active.length,1);});
