import test from 'node:test';import assert from 'node:assert/strict';
import {freshStore} from '../chat-prototype/companion-state.mjs';
import {propose,undo} from '../chat-prototype/companion-tools.mjs';
import {createCompanionAgent,MODEL} from '../chat-prototype/companion-agent.mjs';
import {changePlanner,planningFocus} from './planner-tools.mjs';
import {editPlan,blockTasks} from './planner-state.mjs';
test('capture focus retains selected day and invalid entity IDs never become a target',()=>{const d=freshStore(),s=planningFocus(d,{day:'2026-09-16',view:'projects',projectId:'missing'});assert.equal(s.date,'2026-09-16');assert.equal(s.project,null);});
const raw='Create a Study project, an Exam readiness RPM block, and add Read chapter one to it.';
const op=(collection,fields,id=null,type='create',ref=null)=>({collection,fields,id,type,ref,evidence:[raw]});
const args=operations=>({operations,continuation:false,question:null,choices:[]});
const meta=d=>({raw,conversationId:d.conversations[0].id,now:new Date(2026,8,16,8)});
const create=()=>args([op('projects',{title:'Study'},null,'create','p'),op('blocks',{title:'Exam readiness',projectId:'$p'},null,'create','b'),op('tasks',{title:'Read chapter one',blockId:'$b'})]);
test('date-only capture retains the chosen day without manufacturing a clock',async()=>{const d=freshStore();await changePlanner(d,args([op('tasks',{title:'Read',time:'tomorrow'})]),meta(d));assert.equal(d.entries[0].planned,null);assert.equal(d.entries[0].plannedDate,'2026-09-17');});
const staleDayCorrections=[
 {via:'changePlanner',seed:d=>{editPlan(d,{type:'saveTask',fields:{title:'Meeting',planned:'2026-09-17T03:30:00.000Z'}});d.entries[0].plannedDate='2026-09-17';},
  correct:(d,raw,now)=>changePlanner(d,{operations:[{...op('tasks',{time:'9:15 am'},1,'update'),evidence:[raw]}],continuation:false,question:null,choices:[]},{raw,conversationId:d.conversations[0].id,now}),when:r=>r.plannerReceipts[0].entry.when,plannedDate:null},
 {via:'legacy propose',seed:d=>{const created='Give cash tomorrow at 8pm';propose(d,{operations:[{type:'create',id:null,fields:{title:'Give cash',time:'tomorrow at 8pm',alert:'reminder'},evidence:[created],collection:'entries'}],continuation:false,question:null,choices:[]},{raw:created,conversationId:d.conversations[0].id,now:new Date('2026-09-16T08:00:00+05:30')});},
  correct:(d,raw,now)=>propose(d,{operations:[{type:'update',id:1,fields:{time:'9:15am',alert:'alarm'},evidence:[raw],collection:'entries'}],continuation:false,question:null,choices:[]},{raw,conversationId:d.conversations[0].id,now}),when:r=>r.receipts[0].when,plannedDate:'2026-09-18'}
];
for(const c of staleDayCorrections)test(`clock correction after a stale saved day uses the next future occurrence (${c.via})`,async()=>{
 const d=freshStore();c.seed(d);assert.equal(d.entries[0].plannedDate,'2026-09-17');
 const r=await c.correct(d,'No, make it 915 am',new Date('2026-09-18T07:54:00+05:30'));
 assert.equal(d.entries[0].planned,'2026-09-18T03:45:00.000Z');assert.equal(d.entries[0].plannedDate,c.plannedDate);assert.equal(d.pending,null);assert.match(c.when(r),/9:15 AM/);
});
test('a concrete new task saves while an older proposal remains available',async()=>{const d=freshStore(),old=args([op('tasks',{title:'Meeting',time:'9'},null,'create')]);old.question='9 AM or 9 PM?';await changePlanner(d,old,meta(d));const savedPending=structuredClone(d.pending),requestRaw='Add buy milk';const request={operations:[{collection:'tasks',fields:{title:'Buy milk'},id:null,type:'create',ref:null,evidence:[requestRaw]}],continuation:false,question:null,choices:[]};await changePlanner(d,request,{raw:requestRaw,conversationId:d.conversations[0].id,now:new Date(2026,8,16,8)});assert.equal(d.entries.at(-1).title,'Buy milk');assert.deepEqual(d.pending,savedPending);});
test('a concrete new task also preserves a legacy kindless proposal',async()=>{const d=freshStore(),created='Give cash tomorrow at 8pm';propose(d,{operations:[{type:'create',id:null,fields:{title:'Give cash',time:'tomorrow at 8pm'},evidence:[created],collection:'entries'}],continuation:false,question:null,choices:[]},{raw:created,conversationId:d.conversations[0].id,now:new Date('2026-09-16T08:00:00+05:30')});const correction='Give cash alarm 915',operation={type:'update',id:1,fields:{time:'9:15pm',alert:'alarm'},evidence:[correction],collection:'entries'};propose(d,{operations:[operation],continuation:false,question:'What future time?',choices:[]},{raw:correction,conversationId:d.conversations[0].id,now:new Date('2026-09-18T07:54:00+05:30')});assert.equal(d.pending.kind,undefined);const savedPending=structuredClone(d.pending),requestRaw='Just add Buy milk as a task',request={operations:[{collection:'tasks',fields:{title:'Buy milk'},id:null,type:'create',ref:null,evidence:[requestRaw]}],continuation:false,question:null,choices:[]};await changePlanner(d,request,{raw:requestRaw,conversationId:d.conversations[0].id,now:new Date('2026-09-20T10:17:00+05:30')});assert.equal(d.entries.at(-1).title,'Buy milk');assert.deepEqual(d.pending,savedPending);});
test('manual editor and AI priority edits normalize destination and source order',()=>{const d=freshStore(),a=editPlan(d,{type:'saveEntity',collection:'blocks',fields:{title:'A'}}),b=editPlan(d,{type:'saveEntity',collection:'blocks',fields:{title:'B'}});for(let i=0;i<3;i++)editPlan(d,{type:'saveTask',fields:{title:'Task '+i,blockId:a}});editPlan(d,{type:'saveTask',id:3,fields:{priority:1}});assert.deepEqual(blockTasks(d,a).map(e=>e.id),[3,1,2]);editPlan(d,{type:'saveTask',id:1,fields:{blockId:b}});assert.deepEqual(blockTasks(d,a).map(e=>e.priority),[1,2]);assert.equal(blockTasks(d,b)[0].priority,1);});
test('invalid compound reference never partially creates records',async()=>{const d=freshStore(),before=structuredClone(d),a=create();a.operations[2].fields.blockId='$missing';await assert.rejects(changePlanner(d,a,meta(d)),/reference/);assert.deepEqual(d,before);});
test('sparse entity edits preserve purpose and parent linkage',async()=>{const d=freshStore();await changePlanner(d,create(),meta(d));const b=d.planner.blocks[0];await changePlanner(d,args([op('blocks',{purpose:'Contribute confidently'},b.id,'update')]),meta(d));assert.equal(d.planner.blocks[0].title,'Exam readiness');assert.equal(d.planner.blocks[0].projectId,b.projectId);});
test('question holds complete hierarchy and continuation preserves all operations',async()=>{const d=freshStore(),a=create();a.question='Which chapter?';await changePlanner(d,a,meta(d));assert.equal(d.entries.length,0);assert.equal(d.planner,undefined);await assert.rejects(changePlanner(d,{...create(),operations:create().operations.slice(0,1),continuation:true},meta(d)),/every operation/);await changePlanner(d,{...create(),continuation:true},meta(d));assert.equal(d.entries.length,1);});
test('delete task is recoverable and undo restores the complete planner transaction',async()=>{const d=freshStore();await changePlanner(d,create(),meta(d));const before=structuredClone(d.planner.blocks);const r=await changePlanner(d,args([op('tasks',{},1,'delete'),op('blocks',{},d.planner.blocks[0].id,'delete')]),meta(d));assert.equal(d.entries[0].archived,true);assert.equal(d.planner.blocks.length,0);undo(d,r.undoId);assert.equal(d.entries[0].archived,false);assert.deepEqual(d.planner.blocks,before);});
test('task move updates both block orders and restores as one undo',()=>{const d=freshStore();const a=editPlan(d,{type:'saveEntity',collection:'blocks',fields:{title:'A'}}),b=editPlan(d,{type:'saveEntity',collection:'blocks',fields:{title:'B'}});for(let i=0;i<3;i++)editPlan(d,{type:'saveTask',fields:{title:'Task '+i,blockId:i<2?a:b,priority:i+1}});editPlan(d,{type:'moveTask',id:1,blockId:b,beforeId:3});assert.deepEqual(blockTasks(d,b).map(e=>e.id),[1,3]);assert.equal(blockTasks(d,a)[0].priority,1);editPlan(d,{type:'undo'});assert.deepEqual(blockTasks(d,a).map(e=>e.id),[1,2]);});
test('planner chat uses calendar checks and explicit rechecked conflict override',async()=>{const d=freshStore(),a=args([op('tasks',{title:'Read',time:'today at 10am'})]),calendar=async()=>({status:'ready',start:+new Date(2026,8,13),end:+new Date(2026,9,8),events:[{id:'meeting',title:'Meeting',start:+new Date(2026,8,16,10),end:+new Date(2026,8,16,11)}]});await changePlanner(d,a,meta(d),calendar);assert.equal(d.entries.length,0);assert.equal(d.pending.kind,'planner');await changePlanner(d,{...a,continuation:true},{...meta(d),raw:'Save anyway'},calendar);assert.equal(d.entries.length,1);});
test('recurring completion and reopen through shared commands preserve the series',async()=>{const d=freshStore();await changePlanner(d,args([op('tasks',{title:'Read',time:'today at 10am',recurrence:'daily'})]),meta(d));await changePlanner(d,args([op('tasks',{},1,'complete')]),meta(d));assert.equal(d.entries[0].done,false);assert.equal(d.entries[0].completedOccurrences.length,1);await changePlanner(d,args([op('tasks',{},1,'reopen')]),meta(d));assert.equal(d.entries[0].completedOccurrences.length,0);});
test('malformed multi-call replies are repaired without executing a partial transaction',async()=>{const data=freshStore();let count=0;const call={id:'one',type:'function',function:{name:'respond',arguments:JSON.stringify({message:'No changes requested.',suggestions:[]})}};const agent=createCompanionAgent({apiKey:'fixture',fetchImpl:async(_,o)=>{assert.equal(JSON.parse(o.body).parallel_tool_calls,undefined);return {ok:true,json:async()=>({model:MODEL,choices:[{finish_reason:'tool_calls',message:{tool_calls:++count===1?[call,{...call,id:'two'}]:[call]}}]})};}});const r=await agent(data,'Hello',{conversationId:data.conversations[0].id});assert.equal(r.error,undefined);assert.equal(count,2);assert.equal(data.entries.length,0);});
