const $=id=>document.getElementById(id);
const platform=window.RPM_PLATFORM??{};
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
let state,busy=false,view='chat',conversationId=localStorage.getItem('rpm-conversation'),showArchived=false,focusedDraftId=null,pendingMessage=null,intentHistoryLimit=20;
const intentActionIds=new Map();
function button(text,fn,cls='choice'){const b=el('button',cls,text);b.type='button';b.disabled=busy;b.addEventListener('click',fn);return b;}
function status(text,error=false,{replaceContent=true}={}){const node=$('status');node.textContent=text;node.classList.toggle('error',error);node.setAttribute('role',error?'alert':'status');if(replaceContent&&platform.compactReply&&error&&view==='chat')$('content').replaceChildren(el('p','assistant-text',text));}
function controls(){document.querySelectorAll('#panel button').forEach(b=>b.disabled=busy&&!['home','close','expand','chat-view','plans-view','context-view','history-view','about'].includes(b.id));const canSend=!busy&&!!state&&!!$('message').value.trim();$('send').disabled=platform.menuSend?false:!canSend;$('send').dataset.canSend=String(canSend);platform.onRender?.({view,busy});if(busy)status(state?.captureMode==='glass'?'Saving your words first…':'Thinking it through…');}
function open(){ $('panel').hidden=false;$('launcher').hidden=true;$('launcher').setAttribute('aria-expanded','true');$('message').focus();}
function setView(next){if(next==='plans'&&platform.openPlans){platform.openPlans();return;}view=next;render();}
function draft(text){setView('chat');$('message').value=text;controls();$('message').focus();}
function suggestions(items,origin={}){const row=el('div','actions');for(const s of items??[]){const label=s.label.trim();const action=s.captureAction??platform.suggestionAction?.(s,origin.sourceRaw,origin.at);const b=button(label,action?()=>captureAction(action):()=>turn({type:'message',text:s.text}));b.setAttribute('aria-label',s.label);row.append(b);}return row;}
async function captureAction(action){if(busy)return;try{if(!platform.captureAction)throw new Error('Open this item from Current plans.');await platform.captureAction(action);}catch(error){status(error.message,true,{replaceContent:false});}}
function card(e,{receipt=false,receiptInfo=null}={}){
  const n=el('article',receiptInfo?'entry receipt capture-receipt':receipt?'entry receipt':'entry');const head=el('div','entry-head');const main=el('div','entry-main');if(receiptInfo)main.append(el('p','receipt-status',receiptInfo.status),el('p','receipt-title',receiptInfo.title));else main.append(el('p','entry-title',e.title));main.append(el('p','entry-meta',e.when??(e.kind==='checkin'?'Check-in':'Time not set')));
  const meta=[e.done?e.state==='cancelled'?'Cancelled':'Done':null,e.minutes!==null?`${e.minutes} min ${e.kind==='checkin'?'reported':e.durationSource==='default_estimate'?'estimate · default':'estimate'}`:null,e.recurrence?`Repeats ${e.recurrence}`:null,e.alert?`${e.alert}${platform.native?'':' · preview'}`:null];main.append(el('p','entry-meta',meta.filter(Boolean).join(' · ')));if(e.mood||e.energy)main.append(el('p','entry-meta',[e.mood,e.energy?e.energy+' energy':null].filter(Boolean).join(' · ')));head.append(main);n.append(head);if(e.purpose)n.append(el('p','entry-meta','Purpose: '+e.purpose));
  if(platform.native&&e.alert){const delivery=platform.delivery(e.id);n.append(el('p','delivery',(receipt?'Phone now: ':'')+(delivery?.label??'Not scheduled')));if(!receipt&&delivery?.status==='imported_not_armed')n.append(button('Enable on phone',async()=>{try{await platform.action('arm',{id:e.id});await window.rpmPhoneRefresh();}catch(error){status(error.message,true);}}));else if(delivery?.status==='permission_needed')n.append(button('Allow alerts',()=>platform.action('settings')));}
  const current=state.entries.find(x=>x.id===e.id);const stale=receipt&&(!current||current.archived||JSON.stringify(current)!==JSON.stringify(e));if(stale)n.prepend(el('span','superseded',current?.archived?'Archived · earlier state':'Earlier state · changed since this message'));
  const row=el('div','actions');if(!receipt&&e.kind==='checkin'){row.append(button('Edit check-in',()=>draft(`Update check-in #${e.id} (${e.title}): `)),button('Archive',()=>turn({type:'archive',collection:'entries',id:e.id})));}else if(!receipt){row.append(button('Change time',()=>draft(`Change the time of #${e.id} (${e.title}) to `)),button(e.alert?'No alert':'Add reminder',()=>turn({type:'message',text:`Set the alert for #${e.id} (${e.title}) to ${e.alert?'off':'reminder'}.`})),button('Archive',()=>turn({type:'archive',collection:'entries',id:e.id})));}else if(receiptInfo?.action)head.append(button('Open',()=>captureAction(receiptInfo.action),'quiet'));else head.append(button('Current',()=>setView('plans'),'quiet'));if(!receipt)n.append(row);
  const original=el('details');original.append(el('summary','','Original words'),el('p','',e.raw??''));n.append(original);return n;
}
function plannerReceipt(r){
  if(r.entry)return card(r.entry,{receipt:true,receiptInfo:r});
  const n=el('article','entry receipt capture-receipt'),main=el('div','entry-main');main.append(el('p','receipt-status',r.status),el('p','receipt-title',r.title));
  n.append(main);if(r.action)n.append(suggestions([{label:'Open',text:'',captureAction:r.action}]));return n;
}
const focusKey=id=>`rpm-intent-focus:${id}`;
function setFocusedDraft(id){focusedDraftId=id??null;const key=focusKey(currentConversation().id);if(id)localStorage.setItem(key,id);else localStorage.removeItem(key);}
function intentPage(){const id=currentConversation().id;if(!platform.intentForConversation)return state.intent??{captures:[]};const first=platform.intentForConversation(id,{offset:0,limit:Math.min(intentHistoryLimit,100)}),captures=[...(first.captures??[])];for(let offset=100;offset<intentHistoryLimit&&offset<first.totalCaptures;offset+=100)captures.push(...platform.intentForConversation(id,{offset,limit:Math.min(100,intentHistoryLimit-offset)}).captures);return {...first,captures,hasMore:captures.length<first.totalCaptures,nextOffset:captures.length};}
function intentCaptures(){const id=currentConversation().id;return intentPage().captures?.filter(c=>c.conversationId===id)??[];}
function openDraftAvailable(id){if(!id)return false;const active=c=>c.draft?.id===id&&['draft','review'].includes(c.draft.status);if(intentCaptures().some(active))return true;if(!platform.intentForConversation)return false;const conversation=currentConversation().id,total=platform.intentForConversation(conversation,{limit:0}).totalCaptures??0;for(let offset=0;offset<total;offset+=100)if(platform.intentForConversation(conversation,{offset,limit:100}).captures.some(active))return true;return false;}
function fieldText(field){const labels={purpose:'Purpose',notes:'Notes',time:'Date and time',minutes:'Duration',blockId:'RPM block',projectId:'Project',goalId:'Goal',areaId:'Life area',year:'Year',must:'Must do',priority:'Priority',recurrence:'Repeats',repeatAfterDays:'Repeat after days',alert:'Alert'},label=field.displayLabel??labels[field.name]??field.name,marker=field.userActionId?'your choice':field.origin==='suggested'?'suggested':'your words';if(field.op==='unknown')return `${label}: needs your answer`;if(field.op==='clear')return `${label}: clear · ${marker}`;const raw=field.displayValue??field.value,value=typeof raw==='boolean'?(raw?'yes':'no'):String(raw);return `${label}: ${value} · ${marker}`;}
function intentOperation(op){const box=el('div','intent-operation');const title=op.fields.find(f=>f.name==='title'&&f.op==='set')?.value??op.targetTitle;box.append(el('p','intent-operation-title',title??`${op.kind} ${op.entity}`));const detail=[op.kind!=='create'?op.kind:null,...op.fields.filter(f=>f.name!=='title').map(fieldText)].filter(Boolean).join(' · ');if(detail)box.append(el('p','entry-meta',detail));return box;}
function actionId(action){const key=JSON.stringify(action);if(!intentActionIds.has(key))intentActionIds.set(key,crypto.randomUUID());return intentActionIds.get(key);}
async function runIntentAction(action){
 if(action.kind==='open'){setFocusedDraft(action.draftId);await turn({type:'intentAction',action,actionId:actionId(action)});if(intentCaptures().some(c=>c.draft?.id===action.draftId&&['draft','review'].includes(c.draft.status))){$('message').placeholder='Tell me what to change in this draft';$('message').focus();status('Editing this draft. Your next message will revise it.');}else setFocusedDraft(null);return;}
 await turn({type:'intentAction',action,actionId:actionId(action)});if(action.draftId===focusedDraftId&&!intentCaptures().some(c=>c.draft?.id===focusedDraftId&&['draft','review'].includes(c.draft.status)))setFocusedDraft(null);
}
function intentCaptureCard(capture){
 const row=el('section','message assistant intent-review');row.dataset.messageId=capture.messageId;
 const source=el('div','intent-source');source.append(el('small','intent-kicker','Your words · saved first'),el('p','user-text',capture.raw));row.append(source);
 const draft=capture.draft;if(capture.reply)row.append(el('p','assistant-text dialogue',capture.reply));
 if(capture.status==='captured'){
  const text=capture.lastError?.message?'I kept this thought, but could not prepare a review.':'Your words are safe. The review is not ready yet.';row.append(el('p',capture.lastError?'intent-state error':'intent-state',text));row.append(button('Retry this thought',()=>turn({type:'intentRetry',messageId:capture.messageId}),'quiet'));return row;
 }
 if(!draft){row.append(el('p','intent-state','Captured. No plan change was proposed.'));return row;}
 const review=el('section','intent-draft');review.append(el('small','intent-kicker',draft.status==='committed'?'Saved plan':draft.status==='undone'?'Undone':draft.status==='parked'?'Draft left for later':'Review before saving'));
 for(const op of draft.operations)review.append(intentOperation(op));
 if(draft.schedulePreview?.items?.length){const schedule=el('div','intent-schedule');schedule.append(el('small','intent-kicker','Local date and time preview'));for(const item of draft.schedulePreview.items){const resolved=item.label??item.reason??'Needs review';schedule.append(el('p','intent-schedule-row',`${item.source} → ${resolved}`));for(const assumption of item.assumptions??[])schedule.append(el('p','entry-meta',assumption));}review.append(schedule);}
 if(draft.question)review.append(el('p','intent-question',draft.question.prompt));
 if(draft.review)review.append(el('p','intent-question',draft.review.question));
 const actions=el('div','actions intent-actions');for(const item of draft.actions??[])actions.append(button(item.label,()=>runIntentAction(item.action),item.action.kind==='commit'?'primary':'choice'));review.append(actions);
 if(draft.status==='parked')review.append(button('Review this draft',()=>turn({type:'intentResume',draftId:draft.id,actionId:`resume:${draft.id}:${draft.revision}`}),'quiet'));
 if(draft.status==='committed'){
  review.append(el('p','receipt-status','Saved on this phone. Alert delivery is shown in the plan.'));const opens=(draft.receipt?.plannerReceipts??[]).filter(r=>r.action);for(const receipt of opens)review.append(button(`Open ${receipt.title||receipt.status}`,()=>captureAction(receipt.action),'quiet'));
  if(draft.receipt?.undoId&&draft.receipt.undoId===state.undoId)review.append(button('Undo this save',()=>turn({type:'intentUndo',draftId:draft.id,actionId:`undo:${draft.id}:${draft.revision}`}),'quiet'));
 }
 if(draft.id===focusedDraftId&&['draft','review'].includes(draft.status))review.prepend(el('p','intent-editing','Editing this draft · your next message will revise it.'));
 row.append(review);return row;
}
function messageOrigin(m){const messages=currentConversation().messages,index=messages.indexOf(m);if(index<0)return {};const user=messages.slice(0,index).findLast(x=>x.role==='user');return {sourceRaw:user?.text,at:m.at};}
function messageReceipts(m){return m.plannerReceipts??platform.receiptsForMessage?.(m)??[];}
function messageSuggestions(m,receipts=messageReceipts(m)){return (m.suggestions??[]).filter(s=>!receipts.length||!(s.label?.trim().toLowerCase()==='open'&&s.text?.trim()==='Open the plan I just changed.'));}
function currentConversation(){return state.conversations.find(c=>c.id===conversationId)??state.conversations.find(c=>!c.archived)??state.conversations[0];}
function message(m){
  const row=el('section','message '+m.role);if(m.role==='user'){row.append(el('div','user-text',m.text));return row;}const plannerReceipts=messageReceipts(m);row.append(el('p','assistant-text',plannerReceipts.length&&m.text!=='Saved.'?'Saved.':m.text));for(const r of plannerReceipts)row.append(plannerReceipt(r));if(!plannerReceipts.length)for(const e of m.receipts??[])row.append(card(e,{receipt:true}));
  for(const memory of m.memories??[]){const box=el('div','entry');box.append(el('p','entry-title','Remembered'),el('p','entry-meta',memory.text));row.append(box);}
  if(m.proposal){const finished=state.pending?.id!==m.proposal.id;row.append(el('small','superseded',finished?'Earlier proposal · no longer open':'Proposal · nothing changed yet'));if(finished){const past=el('div','actions');for(const s of m.proposal.choices??[])past.append(el('span','choice',s.label));row.append(past);}}else if(!platform.native)row.append(suggestions(messageSuggestions(m,plannerReceipts),messageOrigin(m)));
  if(m.undoId&&m.undoId===state.undoId)row.append(button('Undo this change',()=>turn({type:'undo',undoId:m.undoId}),'quiet'));
  if(m.error){const prev=currentConversation().messages;const raw=prev.slice(0,prev.indexOf(m)).findLast(x=>x.role==='user')?.text;if(raw)row.append(button('Retry',()=>turn({type:'message',text:raw}),'quiet'));}return row;
}
function legacyPending(glass=false){const p=el('section','pending');p.append(el('h3','',glass?'Classic proposal waiting':'Changes in progress'));for(const op of state.pending.operations){const name=op.fields.title??state.entries.find(e=>e.id===op.id)?.title??op.fields.preference??op.collection;const changes=Object.entries(op.fields).filter(([k])=>!['title','kind'].includes(k)).map(([k,v])=>`${k}: ${v??'clear'}`).join(' · ');p.append(el('div','proposal-row',`${name}${changes?' — '+changes:''}`));}p.append(el('p','',state.pending.question));if(glass)p.append(el('p','view-description','This proposal came from Classic and blocks a separate Glass save until you resolve or leave it.'),button('Continue in Classic',()=>platform.setCaptureMode?.('classic'),'choice'));p.append(button('Leave this proposal',()=>turn({type:'cancel'}),'quiet'));return p;}
function renderChat(content){
  const c=currentConversation();conversationId=c.id;localStorage.setItem('rpm-conversation',c.id);
  if(platform.native&&state.captureMode==='glass'){
    const page=intentPage(),captures=page.captures??[],savedFocus=localStorage.getItem(focusKey(c.id));if(!focusedDraftId&&savedFocus)focusedDraftId=savedFocus;if(focusedDraftId&&!openDraftAvailable(focusedDraftId))setFocusedDraft(null);
    if(!captures.length)content.append(el('p','assistant-text dialogue','What’s on your mind? Your words will be saved before I prepare any plan.'));else{content.append(intentCaptureCard(captures[0]));if(captures.length>1){const earlier=el('details','chat-history');earlier.open=intentHistoryLimit>20;earlier.append(el('summary','',`Earlier captured thoughts · ${captures.length-1}${page.hasMore?' of '+(page.totalCaptures-1):''}`));for(const capture of captures.slice(1))earlier.append(intentCaptureCard(capture));if(page.hasMore)earlier.append(button('Show older captured thoughts',()=>{intentHistoryLimit+=20;render();},'quiet'));content.append(earlier);}}
    if(state.pending)content.append(legacyPending(true));if(c.messages.length){const classic=el('details','chat-history classic-history');classic.append(el('summary','',`Earlier Classic conversation · ${c.messages.length}`));for(const m of c.messages)classic.append(message(m));content.append(classic);}if(c.archived)content.prepend(el('p','view-description','Archived conversation. Restore it from History before replying.'));return;
  }
  if(platform.compactReply){const latest=c.messages.findLast(m=>m.role==='assistant');if(!latest)content.append(el('p','assistant-text dialogue','What’s on your mind?'));else{const rendered=message(latest);rendered.querySelector('.assistant-text')?.classList.add('dialogue');content.append(rendered);}if(state.pending)content.append(legacyPending());return;}
  if(!c.messages.length){const welcome=el('section','welcome');welcome.append(el('h2','','What’s on your mind?'),el('p','','A plan, a change of mind, or something you want me to remember. We can work it out here.'));if(!platform.native)welcome.append(suggestions([{label:'What’s planned?',text:'What do I have planned?'},{label:'Plan something',text:'Help me put a plan together.'},{label:'What do you remember?',text:'What do you remember about my preferences?'}]));content.append(welcome);}
  const log=el('div');log.setAttribute('role','log');log.setAttribute('aria-label','Chat messages');let previous;if(platform.compactReply&&c.messages.length>1){previous=el('details','chat-history');previous.append(el('summary','',`Earlier messages · ${c.messages.length-1}`));for(const m of c.messages.slice(0,-1))previous.append(message(m));}for(const m of platform.compactReply?c.messages.slice(-1):c.messages)log.append(message(m));if(previous)log.append(previous);content.append(log);if(c.archived)content.prepend(el('p','view-description','Archived conversation. Restore it from History before replying.'));
  if(state.pending)content.append(legacyPending());
}
function heading(content,title,description){const head=el('div','view-heading');head.append(el('h2','',title));content.append(head,el('p','view-description',description));return head;}
function recordActions(row,collection,item){row.append(button(item.archived?'Restore':'Archive',()=>turn({type:item.archived?'restore':'archive',collection,id:item.id}),'quiet'));}
function render(){
  if(!state)return;const content=$('content');const frag=document.createDocumentFragment();for(const name of ['chat','plans','context','history'])$(name+'-view').setAttribute('aria-pressed',String(view===name));
  if(view==='chat')renderChat(frag);
  if(view==='plans'){heading(frag,'Current plans',platform.plansDescription??'The latest saved state. Changes affect this test copy only.');const entries=state.entries.filter(e=>!e.archived);if(!entries.length)frag.append(el('p','empty','No entries yet. Tell me what you have in mind.'));for(const e of entries.toReversed())frag.append(card(e));}
  if(view==='context'){
    heading(frag,'Context','Stated preferences and original history. Archive anything you don’t want the AI to use.');frag.append(button(showArchived?'Hide archived':'Show archived',()=>{showArchived=!showArchived;render();},'quiet'),el('h3','','Remembered preferences'));
    for(const m of state.memories.filter(m=>showArchived||!m.archived)){const row=el('div','record'+(m.archived?' archived':''));row.append(el('p','',m.text),el('small','',m.archived?'Archived · excluded from AI context':'Explicitly stated'),button('Edit',()=>draft(`Change my remembered preference "${m.text}" to `),'quiet'));recordActions(row,'memories',m);frag.append(row);}if(!state.memories.length)frag.append(el('p','empty','Nothing remembered yet. Tell me a preference and I’ll keep it here.'));
    if(showArchived){frag.append(el('h3','','Archived entries'));for(const e of state.entries.filter(e=>e.archived)){const row=el('div','record');row.append(el('p','',e.title));recordActions(row,'entries',e);frag.append(row);}}
    frag.append(el('h3','','Original history'));for(const h of state.history.filter(h=>showArchived||!h.archived).toReversed()){const row=el('div','record'+(h.archived?' archived':''));row.append(el('p','',h.raw),el('small','',`${h.source==='cli-import'?'Imported CLI':'Conversation'} · ${h.archived?'archived':new Date(h.at).toLocaleDateString()}`));recordActions(row,'history',h);frag.append(row);}
  }
  if(view==='history'){const head=heading(frag,'Conversations','New conversations keep your plans and memory. Older chats stay available to the AI unless archived.');head.append(button('New chat',()=>turn({type:'new'}),'new-chat'));for(const c of state.conversations.toReversed()){const row=el('div','record'+(c.archived?' archived':'')),glassCount=platform.intentForConversation?.(c.id,{limit:0}).totalCaptures??0,total=c.messages.length+glassCount;row.append(button(c.title,()=>{conversationId=c.id;intentHistoryLimit=20;setView('chat');},'conversation-link'),el('small','',`${total} messages${c.archived?' · archived':''}`));if(c.id!==conversationId||c.archived)recordActions(row,'conversations',c);frag.append(row);}}
  if(view==='about'){heading(frag,'About this prototype','A local assistant, with a recoverable test copy of your data.');const copy=el('div','about-copy');for(const p of ['Your messages, relevant RPM records and explicit preferences go to the existing OpenRouter AI. It can search all unarchived prototype history through tools. Longer history is retrieved when needed, not all sent on every turn.','Imported CLI plans and history are copies. This assistant cannot write to your CLI store or run its alerts. Separate synthetic test datasets are not imported.','Plans, conversations, pending changes and memory survive restarts in private local storage. Archive excludes a record from active AI context; restore brings it back.','Reminder and recurrence cards describe saved settings only. No alarms ring and no external calendars are changed.','The assistant can make mistakes. Inspect current plans, keep original words, and use Undo for the latest change.'])copy.append(el('p','',p));frag.append(copy);}
  if(view==='about'&&platform.native){frag.replaceChildren();heading(frag,'Your pocket assistant','Private phone storage · OpenRouter AI');for(const p of platform.about)frag.append(el('p','about-copy',p));frag.append(button('Phone settings',()=>platform.action('settings')));}
  if(platform.native){const c=currentConversation(),glass=state.captureMode==='glass';const recent=c.messages.at(-1);const items=glass?[]:state.pending?.choices??(recent?.role==='assistant'?messageSuggestions(recent):!c.messages.length?[{label:'What’s planned?',text:'What do I have planned?'},{label:'Plan something',text:'Help me put a plan together.'},{label:'My preferences',text:'What do you remember about my preferences?'}]:[]);$('prompt-choices').replaceChildren(suggestions(view==='chat'&&!c.archived?items:[],recent?.role==='assistant'?messageOrigin(recent):{}));}
  if(platform.goalIdeas&&view==='chat'&&!state.pending&&state.captureMode!=='glass'&&!currentConversation().messages.length){const row=$('prompt-choices').querySelector('.actions');if(row)row.append(button('Goal ideas',platform.goalIdeas));}
  content.replaceChildren(frag);controls();if(!busy)status(state.aiEnabled?'':platform.native?'Connect your AI key in Settings to chat. Saved plans stay available offline.':'AI is not connected. You can inspect saved context.');
}
async function turn(payload){
  if(busy||!state)return;const draftText=$('message').value;
  if(payload.type==='message'&&state.captureMode==='glass'){
    if(!pendingMessage||pendingMessage.text!==payload.text||pendingMessage.focusDraftId!==focusedDraftId)pendingMessage={text:payload.text,messageId:crypto.randomUUID(),focusDraftId:focusedDraftId};
    payload={...payload,messageId:pendingMessage.messageId,focusDraftId:pendingMessage.focusDraftId};
  }
  busy=true;controls();
  if(payload.type==='message'){view='chat';if(platform.compactReply){$('message').value='';localStorage.setItem('rpm-native-draft','');$('message').focus({preventScroll:true});controls();}else{render();$('content').append(message({role:'user',text:payload.text}));$('content').scrollTop=$('content').scrollHeight;}}
  try{const response=await fetch('/api/turn',{method:'POST',headers:{'Content-Type':'application/json','X-RPM-Token':state.csrf},body:JSON.stringify({...payload,version:state.version,conversationId})});const data=await response.json();if(!response.ok){if(data.state){state=data.state;render();}throw new Error(data.error??'Could not finish the request.');}state=data;if(payload.type==='new'){conversationId=data.conversations.at(-1).id;view='chat';}if(payload.type==='message'){view='chat';pendingMessage=null;if($('message').value===draftText)$('message').value='';}busy=false;render();if(payload.type==='message'||payload.type==='new')$('content').scrollTop=platform.compactReply?0:$('content').scrollHeight;return data;}
  catch(e){busy=false;if(platform.compactReply&&!$('message').value){$('message').value=draftText;localStorage.setItem('rpm-native-draft',draftText);}controls();status(e.message==='Failed to fetch'?'The local server is unavailable. Your draft is kept; reconnect and retry.':e.message,true,{replaceContent:state?.captureMode!=='glass'});}
}
$('launcher').addEventListener('click',open);$('close').addEventListener('click',()=>{$('panel').hidden=true;$('launcher').hidden=false;$('launcher').setAttribute('aria-expanded','false');$('launcher').focus();});$('expand').addEventListener('click',()=>{const full=$('panel').classList.toggle('expanded');$('expand').setAttribute('aria-pressed',String(full));$('expand').setAttribute('aria-label',full?'Compact conversation':'Expand conversation');});$('home').addEventListener('click',()=>setView('chat'));for(const name of ['chat','plans','context','history'])$(name+'-view').addEventListener('click',()=>setView(name));$('about').addEventListener('click',()=>setView('about'));
$('message').addEventListener('input',controls);$('composer').addEventListener('submit',e=>{e.preventDefault();const text=$('message').value;if(text.trim())turn({type:'message',text});});$('message').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('composer').requestSubmit();}});
if(platform.native){
  $('panel').hidden=false;$('launcher').hidden=true;
  $('close').addEventListener('click',()=>platform.action('minimize'));
  $('expand').addEventListener('click',()=>platform.action('expand'));
  $('settings').addEventListener('click',()=>platform.action('settings'));
  $('message').value=localStorage.getItem('rpm-native-draft')??'';
  $('message').addEventListener('input',()=>localStorage.setItem('rpm-native-draft',$('message').value));
  new MutationObserver(()=>localStorage.setItem('rpm-native-draft',$('message').value)).observe($('send'),{attributes:true,attributeFilter:['disabled']});
  window.rpmHandleBack=()=>{if(window.rpmDismissMenu?.())return true;if(view!=='chat'){setView('chat');return true;}return false;};
  window.addEventListener('rpm-phone-status',async()=>{if(busy)return;state=await(await fetch('/api/state')).json();render();});
  window.addEventListener('rpm-capture-mode',async()=>{if(busy)return;state=await(await fetch('/api/state')).json();setFocusedDraft(null);render();});
}
fetch('/api/state').then(async r=>{if(!r.ok)throw new Error();const data=await r.json();if(!data.conversations)throw new Error('old_server');state=data;conversationId=currentConversation().id;render();if(platform.native)$('content').scrollTop=platform.compactReply?0:$('content').scrollHeight;}).catch(e=>{open();status(e.message==='old_server'?'The updated companion server is not running here yet.':'Could not connect. Your saved data will return when the server is available.',true);});
