import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {freshStore,openStore,transaction} from './companion-store.mjs';
import {propose,undo,readContext,initialContext} from './companion-tools.mjs';
import {MODEL,createCompanionAgent} from './companion-agent.mjs';
import {createCompanionServer} from './companion-server.mjs';
const now=new Date('2026-09-11T08:00:00+05:30');
const op=(type,id,fields,raw,collection='entries')=>({type,id,fields,evidence:[raw],collection});
const args=(operations,extra={})=>({operations,continuation:false,question:null,choices:[],...extra});
function seeded(){const d=freshStore();const raw='run tomorrow 8am and walk tomorrow 6pm';propose(d,args([op('create',null,{title:'run',time:'tomorrow 8am'},raw),op('create',null,{title:'walk',time:'tomorrow 6pm'},raw)]),{raw,conversationId:d.conversations[0].id,now});return d;}
const call=(name,arguments_)=>({model:MODEL,choices:[{finish_reason:'tool_calls',message:{content:null,tool_calls:[{id:'test-call',type:'function',function:{name,arguments:JSON.stringify(arguments_)}}]}}]});

test('two-plan shorthand edit applies both and undo restores both',()=>{
  const d=seeded();const before=structuredClone(d.entries);const raw='make the run 530 and walk at 9';const result=propose(d,args([op('update',1,{time:'530'},raw),op('update',2,{time:'9'},raw)]),{raw,now});
  assert.equal(d.entries.length,2);assert.match(result.receipts[0].when,/5:30 AM/);assert.match(result.receipts[1].when,/9:00 PM/);assert.equal(d.entries[0].raw,before[0].raw);undo(d,result.undoId);assert.deepEqual(d.entries,before);
});
test('ambiguous compound proposal changes nothing then resolves all operations',()=>{
  const d=seeded();const before=structuredClone(d.entries);const raw='make the run 530 and walk at 9';const operations=[op('update',1,{time:'5:30am'},raw),op('update',2,{time:'9'},raw)];
  propose(d,args(operations,{question:'For the walk, 9 AM or 9 PM?',choices:[{label:'9 AM',text:'9am'},{label:'9 PM',text:'9pm'}]}),{raw,now});assert.deepEqual(d.entries,before);assert.equal(d.pending.operations.length,2);
  operations[1]=op('update',2,{time:'9pm'},'9pm');const result=propose(d,args(operations,{continuation:true}),{raw:'9pm',now});assert.equal(d.pending,null);assert.equal(result.receipts.length,2);assert.match(result.receipts[1].when,/9:00 PM/);
});
test('invalid target cannot partially save another edit',()=>{const d=seeded(),before=structuredClone(d);const raw='change both';assert.throws(()=>propose(d,args([op('update',1,{time:'10am'},raw),op('update',99,{time:'9pm'},raw)]),{raw,now}));assert.deepEqual(d,before);});
test('new ambiguous time produces choice bubbles without a speculative entry',()=>{const d=freshStore(),raw='run tomorrow at 9';propose(d,args([op('create',null,{title:'run',time:'tomorrow at 9'},raw)]),{raw,now});assert.equal(d.entries.length,0);assert.equal(d.pending.choices.length,2);});
test('clock shorthand never rewrites a calendar year as a clock',()=>{
  for(const time of ['September 12, 2026 at 8:00 AM','2026-09-12 at 8:00 AM','September 12, 2026 at 530am']){
    const d=freshStore(),raw='run tomorrow morning';const r=propose(d,args([op('create',null,{title:'Run',time},raw)]),{raw,now});
    assert.equal(d.pending,null,time);assert.equal(d.entries[0]?.plannedDate,'2026-09-12',time);assert.equal(new Date(d.entries[0].planned).getHours(),time.includes('530')?5:8);assert.equal(r.receipts.length,1);
  }
});
test('explicit memory correction and archive are undoable',()=>{const d=seeded(),raw='I prefer running before breakfast';let r=propose(d,args([op('remember',null,{preference:raw},raw,'memories')]),{raw,now});const id=d.memories[0].id;const change='I prefer evening runs';propose(d,args([op('remember',id,{preference:change},change,'memories')]),{raw:change,now});assert.equal(d.memories.length,1);assert.equal(d.memories[0].text,change);r=propose(d,args([op('archive',id,{},'archive','memories')]),{raw:'archive',now});assert.equal(readContext(d,{collection:'memories'}).total,0);undo(d,r.undoId);assert.equal(d.memories[0].text,change);});
test('archived entries excluded from initial and historical context',()=>{const d=seeded();d.history.push({id:'h1',raw:'private old plan',entryIds:[1]});d.entries[0].archived=true;assert.equal(initialContext(d,d.conversations[0].id).entries.length,1);assert.equal(readContext(d,{collection:'history'}).total,0);});
test('archived history and conversations do not leak through duplicate context paths',()=>{const d=seeded(),cid=d.conversations[0].id;d.conversations[0].messages=[{role:'user',text:'obsolete preference'},{role:'assistant',text:'Remembered obsolete preference'}];d.history.push({id:'h',raw:'obsolete preference',response:'Remembered obsolete preference',conversationId:cid,archived:true});assert.equal(initialContext(d,cid).recentMessages.length,0);assert.equal(readContext(d,{collection:'conversations'}).total,0);d.history[0].archived=false;d.conversations[0].archived=true;assert.equal(readContext(d,{collection:'history'}).total,0);});
test('continuation cannot drop another plan and undo preserves subsequent conversation history',()=>{const d=seeded(),raw='change both';const operations=[op('update',1,{time:'7am'},raw),op('update',2,{time:'9pm'},raw)];propose(d,args(operations,{question:'Continue?',choices:[]}),{raw,now});assert.throws(()=>propose(d,args([operations[1]],{continuation:true}),{raw:'yes',now}),/omitted/);const r=propose(d,args(operations,{continuation:true}),{raw:'yes',now});d.history.push({id:'later',raw:'a later message'});undo(d,r.undoId);assert.ok(d.history.find(h=>h.id==='later'));});
test('old history beyond recent window remains searchable and paginated',()=>{const d=seeded();d.history=Array.from({length:30},(_,i)=>({id:i,raw:`item ${i}`,archived:false}));assert.equal(readContext(d,{collection:'history',query:'item',cursor:0}).nextCursor,12);assert.equal(readContext(d,{collection:'history',query:'item 29',cursor:0}).items[0].id,29);});
test('recurrence is saved as preview setting and check-in actual duration is not defaulted',()=>{const d=seeded(),raw='run daily';propose(d,args([op('update',1,{recurrence:'daily',alert:'reminder'},raw)]),{raw,now});assert.equal(d.entries[0].recurrence,'daily');const note='felt tired';propose(d,args([op('create',null,{title:note,kind:'checkin',energy:'Low'},note)]),{raw:note,now});assert.equal(d.entries.at(-1).minutes,null);});
test('private store persists pending proposals and never mutates imported CLI',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rpm-companion-test-'));const input=path.join(dir,'cli.json'),file=path.join(dir,'companion.json');fs.writeFileSync(input,JSON.stringify({version:1,entries:seeded().entries,results:[],interactions:[]}));const before=fs.readFileSync(input,'utf8');const store=openStore(file,{importFile:input});transaction(store,d=>{d.pending={question:'AM or PM?',operations:[]};});const reload=openStore(file,{importFile:input});assert.equal(reload.data.pending.question,'AM or PM?');assert.equal(fs.statSync(file).mode&0o777,0o600);assert.equal(fs.readFileSync(input,'utf8'),before);assert.throws(()=>openStore(input,{importFile:input}));fs.rmSync(dir,{recursive:true});});
test('model tool arguments repaired once; unsupported field never reaches records',async()=>{const d=seeded();let calls=0;const raw='move run to 10am';const agent=createCompanionAgent({apiKey:'synthetic',fetchImpl:async()=>new Response(JSON.stringify(++calls===1?call('propose_changes',args([op('update',1,{dangerous:'oops'},raw)])):call('propose_changes',args([op('update',1,{time:'10am'},raw)]))),{status:200})});const r=await agent(d,raw,{conversationId:d.conversations[0].id,now});assert.equal(calls,2);assert.match(r.receipts[0].when,/10:00 AM/);});
test('read tool accesses older context before conversational reply',async()=>{const d=seeded();let n=0;const agent=createCompanionAgent({apiKey:'synthetic',fetchImpl:async(_url,options)=>{const b=JSON.parse(options.body);if(n++)assert.ok(b.messages.some(m=>m.role==='tool'));return new Response(JSON.stringify(n===1?call('read_context',{collection:'history',query:'',cursor:0}):call('respond',{message:'Here is what I found.',suggestions:[]})),{status:200});}});const r=await agent(d,'What did I say before?',{conversationId:d.conversations[0].id,now});assert.equal(n,2);assert.equal(r.calls[0].tool,'read_context');});
test('network failure is bounded and does not mutate records',async()=>{const d=seeded(),before=structuredClone(d);let n=0;const agent=createCompanionAgent({apiKey:'synthetic',fetchImpl:async()=>{n++;throw new Error('secret should not be shown');}});const r=await agent(d,'move both',{now});assert.equal(r.error,'connection_error');assert.equal(n,1);assert.ok(!r.text.includes('secret'));assert.deepEqual(d,before);});
test('companion uses the requested Luna model without DeepSeek routing or unsupported sampling',async()=>{
  const d=freshStore();const agent=createCompanionAgent({apiKey:'synthetic',fetchImpl:async(_url,options)=>{
    const request=JSON.parse(options.body);assert.equal(request.model,'openai/gpt-5.6-luna');assert.equal(request.tool_choice,'required');assert.equal(request.reasoning.effort,'medium');assert.equal(request.temperature,undefined);assert.equal(request.provider.order,undefined);assert.equal(request.provider.require_parameters,true);assert.ok(request.tools.every(tool=>tool.function.strict===false),'Optional patch fields must remain optional, not strict-schema null padding.');
    return new Response(JSON.stringify(call('respond',{message:'Hello.',suggestions:[]})),{status:200});
  }});assert.equal((await agent(d,'hello',{now})).text,'Hello.');
});
test('HTTP auth, stale versions, journal-before-AI, and restart readback',async()=>{
  const store=openStore();let release;const gate=new Promise(r=>release=r);const server=createCompanionServer({store,agent:async()=>{await gate;return {text:'Hello',suggestions:[]};}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
  try{let s=await(await fetch(origin+'/api/state')).json();const body={version:s.version,conversationId:s.conversations[0].id,type:'message',text:'hello'};const headers={Origin:origin,'Content-Type':'application/json','X-RPM-Token':s.csrf};const denied=await fetch(origin+'/api/turn',{method:'POST',headers:{...headers,'X-RPM-Token':'wrong'},body:JSON.stringify(body)});assert.equal(denied.status,403);const pending=fetch(origin+'/api/turn',{method:'POST',headers,body:JSON.stringify(body)});for(let i=0;i<30&&!store.data.conversations[0].messages.length;i++)await new Promise(r=>setTimeout(r,5));assert.equal(store.data.conversations[0].messages[0].text,'hello');release();s=await(await pending).json();assert.equal(s.conversations[0].messages.length,2);assert.equal((await fetch(origin+'/api/turn',{method:'POST',headers,body:JSON.stringify(body)})).status,409);
  }finally{release();await new Promise(r=>server.close(r));}
});
