import test from 'node:test';import assert from 'node:assert/strict';
import {compilePlannerOperations,createRpmPlanAdapter} from '../adapters/rpm-glass.mjs';
import {structuredRequest,readStructuredResponse} from '../adapters/transport.mjs';
import {seed,field,operation,NOW,turn} from './helpers.mjs';
const approval={actionId:'a1',at:NOW,reviewToken:null};
const draft=ops=>({id:'d1',revision:1,conversationId:'c1',created:NOW,sourceMessageIds:['m1'],operations:ops,guards:{}});
function withCapture(){const d=seed();d.intentV2={captures:{m1:{raw:'Prepare the lesson',at:NOW}}};return d;}
test('compiler orders new parent references before child tasks',()=>{const d=draft([operation([field('title','Lesson'),field('blockId','$b1')]),operation([field('title','A ready lesson')],{opId:'b1',entity:'block'})]);const ops=compilePlannerOperations(d,approval);assert.equal(ops[0].collection,'blocks');assert.equal(ops[1].fields.blockId,'$b1');});
test('compiler never inserts a default duration as user fact',()=>{assert.equal(compilePlannerOperations(draft([operation()]),approval)[0].fields.minutes,null);});
test('compiler preserves sparse patches on updates',()=>{const result=compilePlannerOperations(draft([operation([field('minutes',20)],{kind:'update',targetId:'1'})]),approval);assert.deepEqual(Object.keys(result[0].fields),['minutes']);});
test('compiler rejects cyclic/missing reference dependencies',()=>{assert.throws(()=>compilePlannerOperations(draft([operation([field('title','Lesson'),field('blockId','$missing')])]),approval),/Missing/);});
test('adapter leaves canonical data untouched while calendar review is pending',async()=>{const data=withCapture();const adapter=createRpmPlanAdapter({readCalendar:async()=>({status:'unavailable'}),changePlanner:async d=>{d.entries.push({id:1});d.pending={scheduleReview:'token',question:'Calendar unavailable; keep this time?',choices:[]};return {};}});const result=await adapter.applyPlan({data,draft:draft([operation()]),approval});assert.equal(result.status,'review');assert.equal(data.entries.length,0);assert.equal(data.pending,null);});
test('adapter forwards explicit reviewed calendar token through legacy continuation',async()=>{let argsSeen,rawSeen;const data=withCapture();const adapter=createRpmPlanAdapter({readCalendar:async()=>({}),changePlanner:async(d,args,meta)=>{argsSeen=args;rawSeen=meta.raw;assert.equal(d.pending.scheduleReview,'token');d.pending=null;d.undo={id:'u1'};return {undoId:'u1',plannerChanges:[]};}});const result=await adapter.applyPlan({data,draft:{...draft([operation()]),review:{token:'token'}},approval:{...approval,reviewToken:'token'}});assert.equal(argsSeen.continuation,true);assert.equal(rawSeen,'save anyway');assert.equal(result.status,'committed');});
test('adapter caches duplicate calendar reads only within the current pass',async()=>{let reads=0;const adapter=createRpmPlanAdapter({readCalendar:async()=>{reads++;return {};},changePlanner:async(d,args,meta,read)=>{await read(123);await read(123);d.undo={id:'u1'};return {undoId:'u1',plannerChanges:[]};}});await adapter.applyPlan({data:withCapture(),draft:draft([operation()]),approval});assert.equal(reads,1);await adapter.applyPlan({data:withCapture(),draft:draft([operation()]),approval});assert.equal(reads,2);});
test('old time interpretation must be refreshed rather than silently rebased',async()=>{const adapter=createRpmPlanAdapter({readCalendar:async()=>({}),changePlanner:async()=>({})});await assert.rejects(adapter.applyPlan({data:withCapture(),draft:draft([operation([field('title','Lesson'),field('time','tomorrow at 7pm')])]),approval:{...approval,at:'2026-09-17T04:00:00Z'}}),/STALE_TIME_REVIEW/);});
test('adapter does not overwrite a pending legacy transaction',async()=>{const data=withCapture();data.pending={id:'legacy'};const adapter=createRpmPlanAdapter({changePlanner:async()=>({}),readCalendar:async()=>({})});await assert.rejects(adapter.applyPlan({data,draft:draft([operation()]),approval}),/legacy pending/);});
test('structured request uses required fields, strict schema, no mutating tools or mandatory reasoning effort',()=>{const body=structuredRequest({model:'vendor/test-model',prompt:'p',input:{}});assert.equal(body.response_format.json_schema.strict,true);assert.equal(body.provider.require_parameters,true);assert.equal(body.provider.allow_fallbacks,false);assert.equal(body.tools,undefined);assert.equal(body.reasoning,undefined);});
test('provider model aliases are not treated as semantic validation',()=>{assert.deepEqual(readStructuredResponse({model:'resolved-alias',choices:[{finish_reason:'stop',message:{content:JSON.stringify(turn())}}]}),turn());});
test('truncated provider output cannot create a plan',()=>{assert.throws(()=>readStructuredResponse({choices:[{finish_reason:'length',message:{content:'{}'}}]}),/complete interpretation/);});
