import test from 'node:test';import assert from 'node:assert/strict';
import {createSortPreview,dismissSortPreview,acceptSortPreview} from '../src/sort-preview.mjs';import {seed} from './helpers.mjs';
import {freshStore} from '../../chat-prototype/companion-state.mjs';import {editPlan as realEditPlan,planner} from '../../android-companion/planner-state.mjs';
const data=()=>{const d=seed();d.entries=[{id:1,title:'Choose example',kind:'plan',blockId:null,done:false},{id:2,title:'Make questions',kind:'plan',blockId:null,done:false}];return d;};
const proposal={id:'sort1',selectedTaskIds:[1,2],blocks:[{blockId:null,title:'Lesson ready',projectId:null,taskIds:[1]}],leftUnsorted:[2]};
function editPlan(d,op){const before=structuredClone({entries:d.entries,planner:{...d.planner,undo:null}});if(op.type==='aiDraft'){d.planner.undo=before;d.planner.blocks.push({id:'b1',title:op.blocks[0].title});d.entries[0].blockId='b1';d.planner.drafts.push({id:'sort-record',status:'unreviewed'});}else d.planner.drafts.at(-1).status='accepted';}
test('creating a grouping preview changes neither entries nor groups',()=>{const d=data(),before=structuredClone(d);createSortPreview(d,proposal);assert.deepEqual(d,before);});
test('dismissing a grouping preview cannot mutate canonical grouping',()=>{const d=data(),preview=createSortPreview(d,proposal);const dismissed=dismissSortPreview(preview);assert.equal(dismissed.status,'dismissed');assert.equal(d.entries[0].blockId,null);assert.equal(d.planner.blocks.length,0);});
test('sort approval applies grouping and preserves whole-operation undo',()=>{const d=data(),preview=createSortPreview(d,proposal);acceptSortPreview(d,preview,{revision:1,editPlan});assert.equal(d.entries[0].blockId,'b1');assert.equal(d.entries[1].blockId,null);assert.equal(d.planner.undo.entries[0].blockId,null);assert.equal(d.planner.drafts[0].status,'accepted');});
test('duplicate selected assignments are rejected',()=>{assert.throws(()=>createSortPreview(data(),{...proposal,leftUnsorted:[1,2]}),/duplicate/);});
test('a dropped selected task is rejected',()=>{assert.throws(()=>createSortPreview(data(),{...proposal,leftUnsorted:[]}),/Every selected task/);});
test('stale grouping preview cannot overwrite a subsequent task edit',()=>{const d=data(),preview=createSortPreview(d,proposal);d.entries[0].title='Different';assert.throws(()=>acceptSortPreview(d,preview,{revision:1,editPlan}),/TARGET_CHANGED/);});
test('a failed legacy sort cannot partially mutate canonical entries',()=>{const d=data(),preview=createSortPreview(d,proposal);assert.throws(()=>acceptSortPreview(d,preview,{revision:1,editPlan:(working)=>{working.entries[0].blockId='bad';throw new Error('Invalid sort');}}));assert.equal(d.entries[0].blockId,null);});
test('Jev preview requires an existing block at creation and acceptance',()=>{const d=data();assert.throws(()=>createSortPreview(d,{...proposal,existingOnly:true}),/only existing/);const corrupted={...createSortPreview(d,proposal),existingOnly:true};assert.throws(()=>acceptSortPreview(d,corrupted,{revision:1,editPlan}),/only existing/);assert.equal(d.entries[0].blockId,null);});
test('Jev preview applies only supplied existing links and remains wholly undoable',()=>{const d=freshStore(),blockId=realEditPlan(d,{type:'saveEntity',collection:'blocks',fields:{title:'Lesson ready'}}),first=realEditPlan(d,{type:'saveTask',fields:{title:'Choose example'}}),second=realEditPlan(d,{type:'saveTask',fields:{title:'Make questions'}}),blocksBefore=structuredClone(planner(d).blocks),preview=createSortPreview(d,{id:'jev-sort',selectedTaskIds:[first,second],blocks:[{blockId,title:'Lesson ready',projectId:null,taskIds:[first]}],leftUnsorted:[second],existingOnly:true});const applied=acceptSortPreview(d,preview,{revision:1,editPlan:realEditPlan});assert.equal(applied.changed,true);assert.equal(d.entries.find(e=>e.id===first).blockId,blockId);assert.equal(d.entries.find(e=>e.id===second).blockId,undefined);assert.deepEqual(planner(d).blocks,blocksBefore);realEditPlan(d,{type:'undo'});assert.equal(d.entries.find(e=>e.id===first).blockId,undefined);assert.deepEqual(planner(d).blocks,blocksBefore);});
