import { convexTest } from "convex-test";
import { makeFunctionReference } from "convex/server";
import { describe,it,expect } from "vitest";
import schema from "../convex/schema";
import { sha256 } from "../convex/security";
import { RETENTION_MS } from "../convex/diagnostics";
const modules=import.meta.glob("../convex/**/*.{ts,js}");
const ref=(name:string)=>makeFunctionReference<"mutation">(`diagnostics:${name}`);
const install="22222222-1234-1234-1234-123456789abc";
async function pair(t:ReturnType<typeof convexTest>,legacy=false){const code=await t.action(makeFunctionReference<"action">(legacy?"admin:createPairingCode":"diagnostics:createPairingCode"),{label:"Synthetic diagnostics"});const res=await t.fetch(legacy?"/v1/pair":"/v1/diagnostics/pair",{method:"POST",body:JSON.stringify({code:code.code,installationId:install})});expect(res.status).toBe(200);return {token:(await res.json()).token,code:code.code};}
const event=(n=1)=>({eventId:`diagnostic-${String(n).padStart(20,"0")}`,sessionId:"synthetic-session",operationId:"synthetic-operation",operation:"capture",kind:"console",level:"error",outcome:"error",appVersion:"test",occurredAt:Date.now(),payload:{args:["Synthetic capture words",{error:{message:"offline",stack:"stack:1"}}]}});
const upload=(t:ReturnType<typeof convexTest>,token:string,events:unknown[])=>t.fetch("/v1/diagnostics",{method:"POST",headers:{Authorization:`Bearer ${token}`},body:JSON.stringify({events})});
describe("Private diagnostics",()=>{
  it("requires authentication and exposes no public read route",async()=>{const t=convexTest(schema,modules);expect((await t.fetch("/v1/diagnostics",{method:"POST",body:'{}'})).status).toBe(401);expect((await t.fetch("/v1/diagnostics")).status).toBe(404);expect((await upload(t,"a".repeat(64),[event()])).status).toBe(401);});
  it("pairs once with hashed credentials and cannot upload legacy plans",async()=>{const t=convexTest(schema,modules);const {token,code}=await pair(t);expect((await t.fetch("/v1/diagnostics/pair",{method:"POST",body:JSON.stringify({code,installationId:install})})).status).toBe(401);const devices=await t.run(ctx=>ctx.db.query("diagnosticDevices").collect());expect(devices[0].tokenHash).toBe(await sha256(token));expect(JSON.stringify(devices)).not.toContain(token);expect((await t.fetch("/v1/sync",{method:"POST",headers:{Authorization:`Bearer ${token}`},body:'{"events":[]}'})).status).toBe(401);});
  it("stores full authorized console content, redacts credentials and preserves idempotent retries",async()=>{const t=convexTest(schema,modules);const {token}=await pair(t);const e={...event(),payload:{raw:"Synthetic personal content",apiKey:"DO-NOT-STORE",nested:{password:"DO-NOT-STORE"},url:"https://a:b@example.com/?token=DO-NOT-STORE",args:["Bearer DO-NOT-STORE","sk-or-v1-DO-NOT-STORE-123456"]}};expect(await (await upload(t,token,[e])).json()).toEqual({ack:[e.eventId]});expect((await upload(t,token,[e])).status).toBe(200);const rows=await t.run(ctx=>ctx.db.query("diagnostics").collect());expect(rows).toHaveLength(1);expect(JSON.stringify(rows)).not.toContain("DO-NOT-STORE");expect(rows[0].payload.raw).toBe("Synthetic personal content");});
  it("rejects conflicting IDs and malformed batches atomically",async()=>{const t=convexTest(schema,modules);const {token}=await pair(t);const e=event();await upload(t,token,[e]);expect((await upload(t,token,[{...e,payload:{different:true}}])).status).toBe(400);expect((await upload(t,token,[event(2),{...event(3),level:"invalid"}])).status).toBe(400);expect((await t.run(ctx=>ctx.db.query("diagnostics").collect()))).toHaveLength(1);});
  it("bounds batches and individual payloads",async()=>{const t=convexTest(schema,modules);const {token}=await pair(t);expect((await upload(t,token,Array.from({length:21},(_,i)=>event(i)))).status).toBe(400);expect((await upload(t,token,[{...event(),payload:{raw:"x".repeat(65000)}}])).status).toBe(400);expect((await upload(t,token,[{...event(),payload:{raw:"x".repeat(257000)}}])).status).toBe(413);});
  it("revokes diagnostic devices without touching planner tables",async()=>{const t=convexTest(schema,modules);const {token}=await pair(t);await upload(t,token,[event()]);await t.mutation(ref("revoke"),{installationId:install});expect((await upload(t,token,[event(2)])).status).toBe(401);expect((await t.run(ctx=>ctx.db.query("records").collect()))).toHaveLength(0);});
  it("accepts an existing paired phone and honors legacy revocation",async()=>{const t=convexTest(schema,modules);const {token}=await pair(t,true);expect((await upload(t,token,[event()])).status).toBe(200);await t.mutation(makeFunctionReference<"mutation">("admin:revokeDevice"),{installationId:install});expect((await upload(t,token,[event(2)])).status).toBe(401);});
  it("queries by operation, release and outcome; retention removes expired rows",async()=>{const t=convexTest(schema,modules);const {token}=await pair(t);await upload(t,token,[event()]);const rows=await t.query(makeFunctionReference<"query">("diagnostics:inspect"),{paginationOpts:{numItems:20,cursor:null},operationId:"synthetic-operation",appVersion:"test",outcome:"error"});expect(rows.page).toHaveLength(1);await t.run(async ctx=>{const row=await ctx.db.query("diagnostics").first();await ctx.db.patch(row!._id,{receivedAt:Date.now()-RETENTION_MS-1000});});expect(await t.mutation(ref("prune"),{})).toEqual({removed:1});expect((await t.run(ctx=>ctx.db.query("diagnostics").collect()))).toHaveLength(0);});
});
