// Connect only to the caller's already-identified QA device; no store loading.
export async function motionPage(adb,path){
 const pid=adb('shell','pidof','com.rpm.prototype').toString().trim(),port=adb('forward','tcp:0','localabstract:webview_devtools_remote_'+pid).toString().trim();
 let page;for(let i=0;i<30;i++){const pages=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json();page=pages.find(p=>p.url.includes(path)&&JSON.parse(p.description||'{}').visible);if(page)break;await new Promise(r=>setTimeout(r,100));}if(!page)throw Error('Expected visible surface '+path);
 const ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});let id=0;const pending=new Map();
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id)pending.get(m.id)?.(m);};
 const call=(method,params={})=>new Promise((resolve,reject)=>{const key=++id,timer=setTimeout(()=>{pending.delete(key);reject(Error('Motion probe timed out'));},15000);pending.set(key,m=>{clearTimeout(timer);pending.delete(key);if(m.error||m.result?.exceptionDetails)reject(Error(JSON.stringify(m.error??m.result.exceptionDetails)));else resolve(m.result);});ws.send(JSON.stringify({id:key,method,params}));});
 const ev=async expression=>(await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true})).result.value;
 return {call,ev,close(){ws.close();adb('forward','--remove','tcp:'+port);}};
}
export const motionSampler=`window.qaSample=(trigger,selector,duration=500)=>new Promise(resolve=>{const frames=[],start=performance.now();trigger();const tick=t=>{const e=document.querySelector(selector),s=e?getComputedStyle(e):null;frames.push({ms:Math.round(t-start),height:document.querySelector('.cap-shell')?.getBoundingClientRect().height??innerHeight,layoutHeight:document.querySelector('#panel')?.offsetHeight??innerHeight,footerY:document.querySelector('.composer-area,.edit-actions,#planner-tabs')?.getBoundingClientRect().top,layoutAnimating:document.documentElement.dataset.layoutAnimating==='true',translate:s?.translate,scale:s?.scale,viewportHeight:innerHeight,bodyHeight:document.body.offsetHeight,opacity:s?.opacity,transform:s?.transform,animations:e?.getAnimations().filter(a=>a.playState==='running').length??0});if(t-start<duration)requestAnimationFrame(tick);else resolve(frames)};requestAnimationFrame(tick);})`;
